_test/assign8.go, interp/cfg.go
=> fix: blank identifier cause panic

README.md
- limitation to Go1.11 and Go1.12.
- rlwrap
Fixes #253
Fixes #254
=> doc: improve documentation.

README.md
Add playground examples links.
=> doc: add playground examples.

README.md
=> doc: add a Limitations section in README

README.md
Add community badge to the readme.
=> doc: add community badge.

cmd/goexports/goexports.go
only for internal testing purpose.
=> goexports: allow to generate mapping for devel, beta, and rc.

_test/variadic4.go, interp/cfg.go, interp/run.go, interp/type.go
=> fix: implement variadic using a type category to avoid corruption

interp/cfg.go, interp/interp.go
Sorry, no specific unit test. This issue was debugged and fixed
using `import "github.com/spf13/cobra"`. Blocker for #257
=> fix: correct resolve of type and symbols from imported source package

_test/fun8.go, interp/gta.go
=> fix: add support for out of order declarations of empty global variables

_test/interface10.go, interp/type.go
=> fix: support defining recursive interface types

.travis.yml
allow to build tags to publish binaries.
=> chore: allow to build tags

_test/variadic5.go, interp/run.go
=> fix: support variadic parameters on methods

_test/for6.go, interp/cfg.go, interp/run.go
=> fix: range over string iterates on runes instead of bytes

_test/time5.go
=> test: ensure hour-aligned timezone

_test/interface11.go, example/pkg/pkg_test.go, interp/cfg.go, interp/gta.go, interp/run.go, interp/type.go
=> fix: correct handling of types alias of interfaces

_test/fun9.go, interp/cfg.go, interp/gta.go
=> fix: handle type declaration inside function

_test/range0.go, _test/range1.go, _test/range2.go, interp/cfg.go, interp/run.go, interp/value.go
=> interp: fix range expression handling

_test/a33.go, _test/a34.go, _test/a35.go, _test/a36.go, _test/a37.go, _test/a38.go, _test/a39.go, interp/cfg.go, interp/run.go, interp/type.go
Fixes #394.
Closes #341.
Fixes #396.
=> interp: fix array size assignment type inference

.travis.yml, _test/range3.go, _test/range4.go, _test/range5.go, _test/range6.go, interp/cfg.go, interp/run.go
Note that this change requires dropping Go1.11 support.
Updates #340.
=> interp: fix map range handling

interp/interp.go
=> interp: use io.Reader and io.Writer for REPL parameters

.golangci.toml, cmd/yaegi/yaegi.go, interp/interp.go
=> feature: rename exported func Repl into REPL

_test/ct/ct1.go, _test/ct/ct2.go, _test/ct/ct3.go, _test/tag0.go, cmd/yaegi/yaegi.go, interp/ast.go, interp/build.go, interp/build_test.go, interp/doc.go, interp/interp_consistent_test.go, interp/src.go
=> feature: add support for custom build tags

_test/method28.go, interp/cfg.go
=> fix: do not hide receiver type for method with anonymous receiver

_test/math1.go, cmd/goexports/goexports.go, stdlib/go1_12_math.go, stdlib/go1_13_math.go
=> fix: goexports performs correct conversion on float32 constants

.github/ISSUE_TEMPLATE/bug_report.md
=> doc: fix spelling

_test/str3.go, interp/cfg.go
=> fix: handle index expression on binary string type

_test/ret7.go, interp/run.go
=> fix: automatic type conversion when returning untyped value

_test/time11.go, interp/cfg.go
=> fix: correct isValueUntyped() to handle typed constants

_test/nil1.go, interp/run.go
=> fix: isNil was not forwarding result when used in a branch expression

internal/genop/genop.go, interp/ast.go, interp/cfg.go, interp/interp_eval_test.go, interp/op.go, interp/run.go
Also provide unary operators implementation for constant processing
during parsing, and type checking.
Fixes #481
=> fix: add support for ^ and + as unary operators

CONTRIBUTING.md
=> doc: add explanation about CLA in CONTRIBUTING.md

_test/or0.go, _test/or1.go, interp/cfg.go, interp/dot.go, interp/run.go
Add tests from #474
Fixes #471
=> fix: use branch operation in || and && operators, fix storage for !

interp/doc.go, stdlib/stdlib.go, stdlib/syscall/syscall.go, stdlib/unsafe/unsafe.go
=> doc: document import of source and binary packages

cmd/yaegi/yaegi.go
Hi,
the first word was in lower case. I just recognized this reading the docs.
Cheers!
=> Case sensitivity fix

README.md
Just to make it explicit - yay for Go scripting...
One thing I haven't tested, and so haven't mentioned - does yaegi need go installed, or is everything statically linked into it, so we're extremely portable?
(I'll test later and update the PR)
=> Add an example of yaegi in a shebang line

_test/fun11.go, interp/gta.go
=> fix: handle out of order type declaration for global var declaration

_test/map19.go, interp/type.go
=> fix: handle recursive type definition involving a map object

_test/interface19.go, interp/cfg.go, interp/value.go
=> fix: define a correct zero value for an not initialized interface{}

_test/method31.go, interp/gta.go
=> fix: handle method declaration with forward declared type

_test/type15.go, interp/cfg.go, interp/run.go
=> fix: handle conversion of nil to an interface type

_test/composite7.go, interp/type.go
=> fix: detect field names in struct pointer

cmd/yaegi/yaegi.go, interp/interp.go
=> interp: weaken panics to errors and return panicked values

_test/switch23.go, _test/switch24.go, _test/switch25.go, _test/switch26.go, interp/cfg.go
=> fix: correct control flow graph for some switch statements

_test/struct36.go, interp/cfg.go, interp/run.go, interp/type.go
=> fix: resolve receiver for binary methods on non interface types

_test/struct34.go, _test/struct35.go, interp/run.go, interp/type.go
=> fix: avoid infinite recursion in genFunctionWrapper()

_test/struct37.go, interp/cfg.go
=> fix: resolve embedded method on pointer types

_test/interface27.go, _test/interface28.go, interp/run.go
=> fix: convert literal nil to interface types

README.md
Update supported Go version in the readme.
=> doc: update supported Go version in the readme.

_test/fun12.go, interp/run.go
=> fix: do not attempt to copy data in empty frame at func call

_test/nil2.go, interp/type.go
=> fix: improve handling of nil

_test/fun13.go, interp/cfg.go, interp/run.go
=> fix: handle function output value assigned to interface var

_test/add0.go, _test/add1.go, _test/add2.go, _test/comp1.go, _test/not0.go, _test/not2.go, internal/genop/genop.go, interp/cfg.go, interp/op.go, interp/type.go, interp/value.go
Assign to interface may require to wrap operation results in a
valueInterface.
Improve test coverage.
Fixes #612.
=> fix: improve setting of interface objects

_test/bin4.go, interp/run.go
=> fix: store the result of a bin function call in frame

_test/assign11.go, _test/assign12.go, interp/ast.go, interp/cfg.go, interp/interp_consistent_test.go, interp/type.go
=> fix: check that a function returns the correct number of values

_test/variadic6.go, interp/run.go
=> fix: handle set of variadic arg list for a ... value

_test/const11.go, interp/cfg.go, interp/gta.go, interp/scope.go
=> fix: handle constant declarations inside function scopes

cmd/yaegi/yaegi.go
Zero sized scripts panic so I added a length check and used bytes package.
=> add repl input bounds check

_test/fun21.go, _test/fun22.go, interp/ast.go, interp/cfg.go, interp/interp_consistent_test.go, interp/type.go
=> fix: check the number of argument passed and returned to functions

_test/struct46.go, interp/run.go
This PR fixes the case where a recursive struct is assigned on struct creation by adding recursion handling the sparse composite creation.
=> fix: compose recursion

_test/struct47.go, _test/struct48.go, interp/cfg.go, interp/run.go, interp/value.go
This PR fixes/adds the ability to call a function on a recursive struct.
Fixes #660
=> fix: recursive struct function call

_test/interface43.go, interp/run.go
This adds specific handling for a nil interface conversion.
=> fix: handle nil interface conversion

_test/make2.go, interp/run.go
`make` must allow uint and int `len` can `cap` values.
=> fix: allow uint in make len and cap

Makefile, _test/unsafe0.go, _test/unsafe1.go, _test/unsafe2.go, _test/unsafe3.go, _test/unsafe4.go, cmd/yaegi/yaegi.go, interp/interp.go, interp/interp_consistent_test.go, interp/interp_file_test.go, interp/run.go, stdlib/unsafe/unsafe.go
This implements the first step of supporting unsafe. Support for the other unsafe functions still needs to be added.
=> feature: unsafe type conversion

.golangci.toml, .travis.yml, cmd/goexports/goexports.go, internal/genop/genop.go, interp/ast.go, interp/build.go, interp/cfg.go, interp/dot.go, interp/example_eval_test.go, interp/interp.go, interp/interp_eval_test.go, interp/run.go, interp/scope.go, interp/src.go, interp/type.go, stdlib/stdlib.go, stdlib/syscall/syscall.go, stdlib/unsafe/unsafe.go
Update golangci-lint to v1.27.0 (the version is in the [CI](https://travis-ci.com/github/containous/yaegi))
=> chore: update linter.

_test/assign15.go, interp/cfg.go, interp/interp_consistent_test.go, interp/type.go
=> fix: do type check on assignment

_test/issue-772.go, interp/run.go
=> fix: apply method receiver offset when generating interface wrapper

_test/issue-776.go, interp/run.go, interp/type.go
=> fix: compositeSparse handles fields of interface kind

.golangci.toml, interp/ast.go, interp/interp_test.go, interp/scope.go, interp/type.go
Update golangci-lint to v1.29.0
=> chore: updated linter

.golangci.toml, cmd/yaegi/yaegi_test.go
Disable nlreturn. Fix one comment.
=> chore: update golangci-lint config

interp/interp.go
=> fix: keep atomic counter aligned on 64 bits boundary

_test/const16.go, interp/typecheck.go
=> interp: fix division for const

_test/const18.go, interp/cfg.go
=> fix: perform constant type conversion when required

_test/select14.go, interp/run.go
=> fix: correct handling of select comm clause with empty body

cmd/yaegi/test.go
This applies to -syscall, -unsafe and -unrestricted flags with the
corresponding env variables YAEGI_SYSCALL, YAEGI_UNSAFE and
YAEGI_UNRESTRICTED, already used in the same way for the run
sub-command.
=> feature: use environment in addition to flags to control test options

.goreleaser.yml
Publish homebrew-tap recipe to https://github.com/traefik/homebrew-tap
=> chore: add homebrew-tap recipe

_test/composite14.go, interp/run.go
=> interp: handle explicit nil values in literal composite values

interp/run.go
The execution flow is such that a node can end up running several chained exec
funcs, some of which actually originate from other nodes. For example, in:
var m []int // L0
println("hello world") // L1
m[0] = 1 // L2
the offending code is on a node on line 2 (out of range error). However, since
the assignment to m is part of the execution flow of the variable m, we'll get
the panic when running all the chained exec funcs attached to the node for m on
line 0.
Which is why, when that happens, we need to look for the actual node (the one on
L2) where the offending instruction originates from, in order to
properly report the origin of the panic.
Fixes #546
=> interp: on panic, look for node where offending exec originated from

interp/interp_eval_test.go, interp/typecheck.go
=> interp: apply type conversion on untyped variable at run

_test/addr2.go, interp/run.go
=> interp: handle getting address of interpreter interface value

interp/cfg.go, interp/interp_eval_test.go
=> interp: fix parsing of assign to dereferenced pointer

_test/assert1.go, interp/run.go
=> interp: support two more type assertion cases

_test/composite15.go, interp/run.go
=> interp: enable type assertion from empty interface into slice

_test/composite15.go, interp/cfg.go, interp/run.go
=> interp: add support for binary composite slice

interp/cfg.go, interp/interp_eval_test.go
=> interp: handle aliased string used as a slice

_test/const25.go, interp/cfg.go
=> interp: do not check properties of incomplete types

extract/extract.go, extract/extract_test.go, extract/testdata/6/src/guthib.com/bar/main.go, extract/testdata/6/src/guthib.com/baz-baz/baz.go, extract/testdata/6/src/guthib.com/baz-baz/go.mod
=> fix #1056, extract: replace the code for get package name.

interp/cfg.go, interp/type.go
=> interp: fix method lookup for aliased types

_test/issue-1089.go, interp/type.go
=> interp: fix type string extraction for wrapped constants

_test/issue-1115.go, interp/cfg.go
=> interp: fix goto label by not overwriting destination

_test/issue-1093.go, interp/interp_consistent_test.go, interp/typecheck.go
=> interp: improve type checking for "+" operator

interp/interp_export_test.go, interp/run.go
=> interp: fix calling of variadic binary methods

_test/issue-1134.go, interp/value.go
=> interp: avoid panic in output value generation for recursive types

_test/issue-1136.go, interp/type.go
=> interp: fix detection of binary types implementing interfaces

_test/append3.go, _test/issue-1128.go, interp/run.go, interp/type.go
=> interp: fix append a slice on binary slice

interp/ast.go, interp/interp_eval_test.go
=> Add a newline after src in wrapInMain

_test/append4.go, interp/type.go, interp/value.go
=> interp: fix handing nil when appending to a slice

_test/issue-1177.go, interp/typecheck.go
=> interp: fix type checking of address of multi dimension array

.github/workflows/go-cross.yml, .github/workflows/main.yml, .golangci.toml, interp/typecheck.go
- update golangci-lint to v1.41.1
- fix GitHub action cache configuration
=> chore: update linter

_test/issue-1202.go, interp/run.go
=> interp: fix handling returned func values

_test/issue-1205.go, interp/run.go
=> interp: fix handling of interface values in variadic calls

interp/gta.go
=> interp: fix package lookup for type analysis of local types

interp/interp_eval_test.go, interp/run.go, interp/typecheck.go
=> interp: fix append with 1 argument

_test/alias2.go, interp/cfg.go, interp/gta.go, interp/interp.go, interp/scope.go, interp/src.go, interp/type.go, interp/typestring.go
This completes the types constructors, cleaning up `nodeType`.
=> interp: complete type constructors

interp/run.go
This change fixes a regression introduced by PR #1192 in a program using
https://github.com/NYTimes/gziphandler which defines several types
implementing stdlib interfaces. We do not implement a wrapper
if we see that a type already implements an interface, except that
it can be falsly reported by reflect in case of a struct with
embedded interface field. We need to force the wrapper generation
in this case.
The problem occurs only for wrappers on struct, not on pointers or
other indirection types.
=> interp: fix interface wrapper for struct types

interp/type.go
This comes from experiments looking into #1259 where incomplete twice seen types are marked as complete. To mitigate the problem instead of a map of seen types in `nodeType` a slice is used as a cheap way to keep track of our current path through the node tree.
=> interp: handle recursive and incomplete seen types in nodeType

_test/issue-1308.go, interp/run.go
=> interp: fix populating array of interfaces

interp/run.go, interp/value.go, stdlib/unsafe/unsafe_go1.17.go
No functional change. Just simpler and faster.
=> interp: replace value.Type().Kind() by value.Kind()

_test/cli1.go, _test/cli2.go, _test/cli3.go, _test/cli4.go, _test/cli5.go, _test/cli6.go, _test/file_access.go, _test/io2.go, _test/issue-1187.go, _test/issue-1260.go, _test/issue-558.go, _test/os0.go, cmd/yaegi/run.go, cmd/yaegi/yaegi_test.go, internal/cmd/genop/genop.go, interp/dot.go, interp/interp_consistent_test.go, interp/interp_eval_test.go, interp/interp_file_test.go, interp/program.go, interp/src_test.go
=> interp: get rid of deprecated stdlib package ioutil

_test/issue-1320.go, interp/run.go, interp/typecheck.go
=> interp: fix setting of interface value from nested function calls

_test/issue-1326.go, interp/run.go
=> interp: fix nested calls with variadic interfaces

_test/issue-1328.go, interp/type.go
=> interp: fix derivation of type of slice expression of binary object

_test/issue-1337.go, interp/run.go
=> interp: improve type switch on binary interfaces

_test/issue-1332.go, interp/run.go
=> interp: make methods passed as value preserve receiver

_test/issue-1364.go, interp/value.go
=> interp: fix interface conversion from binary call

_test/issue-1375.go, interp/run.go
=> Prevent variadic arguments from being wrapped as function

_test/issue-1378.go, interp/cfg.go
=> interp: fix redeclaration scope issue

_test/issue-1408.go, interp/type.go, interp/typecheck.go
=> interp: improve type checking for defined types

_test/issue-1421.go, interp/typecheck.go
=> interp: improve type checking when comparing aliased types

_test/gen10.go, interp/type.go
Related to issue https://github.com/traefik/traefik/issues/9231
=> interp: fix generic check on nil function
