traefik/yaegi

- _test/interface9.go
- interp/run.go
If assign destination type is a binary interface, get source value from
interface wrapper.
Fix #251
> fix: correct assign to binary interface value

- _test/a30.go
- _test/a31.go
- interp/ast.go
A blank key index is inserted during AST construction, to make
`for range X` equivalent of `for _ = range X` which works well.
Fix #258
> fix: support 'range' with no index and value assigned

- .golangci.toml
- interp/build.go
- interp/build_test.go
- stdlib/stdlib.go
- stdlib/syscall/syscall.go
- stdlib/unsafe/unsafe.go
Display a better message when a version is not supported.
Allow to use `devel`, `beta`, and `rc` versions.
Related to #304, #309
> interp/build: improve Go version handling.

- interp/ast.go
- interp/build.go
- interp/build_test.go
- interp/interp.go
- interp/src.go
Use of build.Context to handle custom build tags. Let user define a list of build tags in interpreter options.
Fixes #307
> interp/build: support custom build constraints.

- .gitignore
- .goreleaser.yml
Add `goexports` command to the archives published in the [release section](https://github.com/containous/yaegi/releases)
The content of one archive (ex: `yaegi_vx.x.x_linux_amd64.tar.gz`) will be:
```
.
├── goexports
├── LICENSE
└── yaegi
```
> chore: add goexports to the archive.

- interp/cfg.go
The (unexpected) panic still occurs, but now conveys the exact
location in input source which triggered the panic.
It improves diagnostics and will help to investigates problem
occuring during CFG pass.
> feature: locate origin of CFG panic in input source

- _test/method21.go
- _test/method22.go
- _test/method23.go
- _test/struct12.go
- _test/struct15.go
- _test/struct19.go
- _test/type12.go
- _test/type13.go
- _test/type14.go
- interp/gta.go
- interp/interp.go
- interp/src.go
For global assign expressions, it may be necessary to re-iterate
GTA, in particular when source type is defined later.
This change allows gta() to return the list of ast nodes to revisit
prior to enter in CFG.
A number of related tests are added, or fixed (missing output).
Fix #331
> fix: iterate on global type analyis when necessary

- _test/a32.go
- _test/composite0.go
- _test/composite1.go
- _test/composite2.go
- _test/method24.go
- _test/select0.go
- _test/struct24.go
- _test/struct25.go
- _test/time8.go
- interp/cfg.go
- interp/interp_eval_test.go
- interp/run.go
- interp/scope.go
- interp/type.go
Handle global assign expressions involving struct fields or method.
Improve handling of out of order.
Improve detection of use of untyped nil.
Increase test coverage.
Fix #269
Fix #337
Not able yet to import "go.uber.org/zap", "github.com/spf13/cobra" or
other complex packages.
> fix: improve handling of global declarations, possibly out of order

- _test/assign9.go
- interp/run.go
- interp/type.go
For functions used internally in the interpreter the frame type
is a node pointer, correctly set by frameType() rather than TypeOf().
Fix #338
> fix: assign a function value to a pre-declared variable

- _test/fun6.go
- _test/method25.go
- _test/method26.go
- _test/struct26.go
- _test/struct27.go
- _test/struct28.go
- interp/cfg.go
- interp/gta.go
- interp/run.go
- interp/scope.go
- interp/type.go
Provide enough informations in created incomplete symbol/type to
make sure it can be completed by finalize() method.
Make sure that incomplete type declarations are revisited.
Fix #343
> fix: improve handling of out of order declarations

- _test/ptr7.go
- interp/cfg.go
When derefencing a binary object, the type must be computed using
typ.rtype.Elem() rather than typ.val (for non-binary objects).
Fix #348
> fix: correct computation of type when dereference a binary object

- _test/fun6.go
- interp/cfg.go
The correction here consists simply to compute the function signature
type before entering the fuction local scope.
Fix #346
> fix: avoid collision between package names and function args

- _test/var8.go
- interp/cfg.go
- interp/gta.go
- interp/interp.go
- interp/scope.go
- interp/type.go
In nodeType(), in presence of a selector expression, the logic was broken
for complex expressions. We now first compute the type of the left part
of the selector, then perform a lookup operation on it.
We now store the package path in type rather than symbol, to allow the
above on srcPkgT and binPkgT.
Fix #359
> fix: global variable init from selector expression

- _test/recurse0.go
- interp/type.go
The conversion of interpreter type to reflect.Type now encodes a
recursive struct by an interface{} to avoid infinite loop.
A previous change fixed the problem for pointers to struct only,
now the refType() function addresses the problem globally:
arrays, maps, functions, channels, sub-structures, direct or
indirect cycles.
Note: further fixes may be necessary to properly get or set field
data of recursive structures. This will be addressed in a separate
change.
Fix #361
> fix: conversion of type to reflect.Type avoids recursive loop

- _test/map18.go
- _test/var7.go
- interp/cfg.go
- interp/run.go
- interp/type.go
The builtin type computation is now impletemented in nodeType()
instead of cfg(), to be applied in global declarations involving
builtin calls.
Fix #357
> fix: init global var from builtin

- _test/c1/c1.go
- _test/c2/c2.go
- _test/import6.go
- interp/interp.go
- interp/interp_consistent_test.go
- interp/src.go
Cyclic dependencies are forbidden in go packages. Detecting them
avoids infinite loops and stack overflow in interpreter.
A map of read directories is added in interpreter context to
dectect an import cycle (same directory opened twice while
importing).
> feature: detect import cycle

- _test/copy1.go
- _test/ptr_array0.go
- _test/ptr_array1.go
- _test/ptr_array2.go
- _test/ptr_array3.go
- interp/cfg.go
- interp/run.go
- interp/value.go
Add array pointer support for index expressions (get and set), slice
expressions and copy() builtin. Provide related test cases.
Fix #368
> fix: support array operations on array pointers

- _test/shift1.go
- _test/shift2.go
- interp/cfg.go
- interp/type.go
Make an exception for shift operators when computing the type and
checking operands type consistency.
Fix #308
> fix: shift operator inherits its type from first arg only

- _test/method27.go
- interp/cfg.go
- interp/run.go
- interp/type.go
lookupBinMethod was skipping methods where receiver is a pointer
on a struct field. A method accessor function at runtime is added
for this case: getPtrIndexSeq.
Fix #264
> fix: binary method lookup works for struct field pointer receiver

- _test/alias1.go
- interp/gta.go
The incomplete status of the aliased type needs to be forwarded to the destination type.
Fix #378
> fix: handle forward declaration of alias type

- interp/cfg.go
- interp/interp_eval_test.go
This prevents the runtime panic that otherwise occurs when a symbol that is referenced in a source is not present in the symbol map.
> interp: don't panic for undefined types

- _test/shift3.go
- interp/cfg.go
- interp/interp_eval_test.go
- interp/type.go
For the following operators: <<, >>, <<=, >>=, untyped constant
values are accepted if they are convertible to int and unsigned.
For example, `1 << 1.0` and `1.0 << 1` are valid but `1 << 1.1`
is not.
This change ensures the required properties are checked for untyped
constants and that result is properly converted and propagated.
Unit tests are updated to match the behaviour of the official go compiler.
Note: in the official go compiler, there may be an inconsistency in
the way untyped constants are processed, as the above behaviour
applies only for shift operations, not other bits operations. For
example, `1.0 & 1` is forbidden.
Fix #278
> fix: correct automatic type conversion for untyped constants

- _test/var9.go
- interp/cfg.go
- interp/type.go
The computation of slice expression is moved in nodeType to be
applied globally.
Fixes #316
> fix: compute type of slice expression globally

- _test/closure8.go
- interp/cfg.go
> fix: generate closures for literal functions in CFG

- interp/interp.go
Relocate Interpreter.id and frame.id at start of struct to
guarranty proper address alignment for all architectures.
Tested on armv7l (32 bits) where it avoids panicing.
> fix: properly align atomic counters

- _test/interface12.go
- interp/run.go
Apply internal conversion to valueInterface when assigning
a litteral composite to an interface object.
Fixes #430
> fix: assign a literal composite to an interface object

- _test/composite3.go
- _test/composite4.go
- interp/cfg.go
- interp/run.go
The type assertion type is deduced from the full parse of type expression, not only the type name lookup. A variant of typeAssert is added for the case of testing the assertion but not using the result var.
Fixes #431
> fix: handle type assertion from literal interface type

- _test/interface12.go
- interp/run.go
- interp/value.go
Dynamic type was lost when an interface was set from another
interface. Fix genValueInterface() to always find out concrete
type value, by walking interface indirections.
Fixes #436
> fix: correct handling of dynamic type for interface values

- _test/fun10.go
- interp/cfg.go
- interp/interp_eval_test.go
- interp/run.go
- interp/value.go
When generating a nil function, wrap a typed nil value in a node
so it can be handled as other interpreter functions.
Test nil value on wrapper rather than on non-nil node wrapper.
Fixes #437
> fix: handle nil function closure

- _test/switch21.go
- interp/cfg.go
For imported packages, types are defined by a selector expression
instead of an identificator (i.e. fmt.Formatter). Add support for
selector in type switch clause parsing.
Fixes partially #424 (in combination with #440)
> fix: handle selector expression in type switch

- _test/for7.go
- _test/if2.go
- interp/cfg.go
- interp/interp_consistent_test.go
- interp/type.go
Add condition type check in post-processing of CFG for
if and for statements. Add an isBool() helper function
which also accepts boolean channel values.
Fixes #438
> fix: detect non boolean condition for IF and FOR statements

- _test/switch22.go
- interp/cfg.go
Use node.isType() to check the type status of case clause,
simpler and more robust logic.
Fixes #449
> fix: improve type switch clause with assign

- _test/foo-bar/foo-bar.go
- _test/import7.go
- interp/cfg.go
- interp/gta.go
In import statement, the implicit package name must be a valid
go identifier, even if the base name of the package path includes
non-letter characters.
This change extract the package name from a regular expression
matching an identifier conform to the Go specification.
Partly fixes #455
> fix: implicit import package name was not correctly generated

- _test/interface18.go
- interp/cfg.go
- interp/type.go
When checking types, do not always check for strict equality between
method sets, but in case of concrete type, check if its method set
*contains* the interface method set.
Fixes #457
> fix: improve interface type checks using method sets

- interp/cfg.go
- interp/type.go
When checking if a node is a struct, test first the type category
to avoid missing recursive struct emulated by interface{}.
Avoid collision between type and field name in imported packages
by ensuring package selectors checks are applied on package symbols
only.
Fixes #455
> fix: struct type detection, collision between field and type name

- _test/str4.go
- interp/cfg.go
The detection of untyped occurs on constant numerical values.
Fixes #456
> fix: detect untyped values when importing from binary packages

- _test/struct29.go
- _test/struct30.go
- interp/gta.go
- interp/run.go
- interp/type.go
> fix: emulate struct by interface{} only for recursive struct types

- _test/nil0.go
- interp/cfg.go
Types may be factored in a function declaration, like in
func f() (a, b, c string)
vs
func f() (a string, b string, c string)
This requires a method to correctly extract the nth parameter type.
This change brings such method fieldType to compute the returned nil type value.
Fixes #464
> fix: correct type extraction for returned value

- _test/bin2.go
- interp/cfg.go
- interp/run.go
Detect the presence of constant expression for unary operators and
perform computation of result during compile stage instead of exec
stage. It was already done correctly for binary operators.
Apply automatic type conversion not only to literal values but
also to arbitrary expressions where all members derive from a
predefined constant at compile stage.
Fixes #470
> fix: apply automatic type conversion to constant expressions

- _test/for8.go
- _test/primes.go
- interp/cfg.go
- interp/scope.go
During CFG, store internal state for break and continue statements in
scope instead of global, to avoid corruption due to nested loops.
Fixes #450
> fix: continue statement was not applied correctly

- _test/method29.go
- _test/method30.go
- interp/cfg.go
- interp/gta.go
- interp/run.go
- interp/type.go
Do not attempt to pass the receiver as method first argument if
the binary method was obtained from a non-interface object
selector, as reflect returns in that case a function where the
receiver is implicit.
Fixes #488
> fix: handle binary methods where receiver is implicit

- _test/var10.go
- _test/var11.go
- interp/run.go
In assign(), if destination symbol is "_", then
skip the assignment, which avoids type mismatch.
Fixes #490
> fix: allow reuse of _ symbol in the same scope

- _test/b1/foo/foo.go
- _test/b2/foo/foo.go
- _test/import8.go
- interp/cfg.go
- interp/gta.go
- interp/interp.go
- interp/scope.go
- interp/src.go
- interp/type.go
Use pkgID (the full import path) rather than just the basename as the key
of source packages map. It avoids false cycle detection when importing
a/b/foo and c/d/foo.
Fixes #492.
> fix: import different source packages with same base name

- _test/type16.go
- _test/type17.go
- interp/interp.go
- interp/type.go
Define byte as an alias to uint8 and rune as an alias to int32,
as per Go specification, instead of defining byte and rune as separate
types.
Fixes #505
> fix: correct behavior for rune and byte types

- _test/composite5.go
- _test/composite6.go
- _test/ct1/ct1.go
- interp/cfg.go
Avoid type interference when setting values from expressions
involving operators. Make sure to propagate constant values from
source packages for constant folding.
Fixes #507
> fix: correct type inference in composite literal init

- _test/const6.go
- _test/const7.go
- interp/ast.go
- interp/cfg.go
- interp/gta.go
- interp/interp_eval_test.go
- interp/value.go
The value of constants is now computed early in global type analysis,
in order to complete parsing where constants are used in type
definition. This is achieved by invoking interp.cfg() on the constant
declaration subtree.
Obsolete rtypeExpr and rvalueExpr node kinds are suppressed.
In TestEvalBuiltin, use separate variables to avoid interferences
between declarations, as the test cases use the same interpreter
context.
Fixes #510
> fix: correctly handle constant init for further type declarations

- _test/a40.go
- interp/run.go
Convert the numerical index value to int according to its source
type.
Fixes #513
> fix: correctly handle arbitrary type of literal array index

- _test/a41.go
- _test/and3.go
- _test/chan8.go
- _test/map20.go
- _test/or2.go
- _test/ptr8.go
- _test/struct31.go
- interp/run.go
- interp/type.go
Although the branching logic is correct for boolean data, the result
(true or false) was not always stored and was set to the default value
(false). This is fixed for struct fields, array elements,
channel objects, pointer elements and map elements.
Credits to @dusmart who identified the problem and provided a first
analysis and a fix proposal.
Fixes #517
> fix: correctly store  boolean result for branching operations

- _test/assign1.go
- _test/bad0.go
- _test/complex3.go
- _test/const10.go
- _test/const8.go
- _test/const9.go
- _test/map19.go
- interp/cfg.go
- interp/gta.go
- interp/interp.go
- interp/interp_consistent_test.go
- interp/src.go
- interp/type.go
Depending on how declarations are ordered, more than 1 retry of
Global Type Analysis pass may be required. The logic has been
changed to retry until all missing symbols are solved or a loop
definition is detected.
A few unit test has been fixed as well.
Fixes #515
> fix: re-apply GTA until all global types/constants are defined

- _test/interface20.go
- _test/interface21.go
- _test/interface22.go
- _test/interface23.go
- _test/interface24.go
- _test/interface25.go
- _test/interface26.go
- interp/cfg.go
- interp/run.go
Correctly wrap values in interfaceValue in []interface{} and
map[]interface{} kind of types. Added related tests.
Fixes #527
> fix: handle interface values in map and arrays

- _test/struct32.go
- _test/struct33.go
- interp/cfg.go
- interp/interp_eval_test.go
- interp/run.go
- interp/src.go
- interp/type.go
Functions in struct fields are wrapped in binary functions, in
order to allow interchange between runtime and interpreter context.
But in this process, the original type of function returned objects
is lost (replaced by anonymous reflect types), making impossible to
perform method resolution (based on type names).
The solution to this problem is to "unwrap" struct field function
types, to preserve the necessary information, and to keep along
the original type reference.
Fixes #525
> fix: handle use of functions in struct fields

- _test/type18.go
- _test/type19.go
- interp/cfg.go
- interp/run.go
- interp/type.go
Handle index expressions to parse map of array objects when initializing
a variable. Improve the detection of type node in composite literal
expressions (sparse or not).
Fixes #532.
> fix: correctly init variables from index expressions

- _test/defer4.go
- interp/ast.go
- interp/cfg.go
- interp/run.go
The control flow graph was incorrect for defer statements, some
defer call dependencies could be missing. This is fixed by generating
the CFG in the same way as regular calls, and handling defered calls
in call generators.
Fixes #500.
> fix: correct control flow graph for defer statements

- _test/map21.go
- _test/map22.go
- _test/map23.go
- interp/run.go
- interp/value.go
Properly detect use of _ var use in expressions involving getIndex,
and avoid to attempt to store data.
Fixes #536.
> fix: do not attempt to store data in _ var

- _test/bin3.go
- interp/run.go
The optimisation to write the result of a function call directly
to variable location must not be enabled for assign operator
expressions such as "+=", "-=", etc. Just limit it to regular
assign expressions.
Fixes #541.
> fix: do not overwrite input for assign operators

- _test/cli2.go
- interp/run.go
When a func call is deferred, the function is always wrapped, thus
embedding the receiver paramater in case of a method. In that case,
avoid to pass the receiver again in the arguments.
Fixes #556.
> fix: do not pass twice the receiver in deferred method calls

- _test/for10.go
- _test/for11.go
- _test/for12.go
- _test/for13.go
- _test/for14.go
- _test/for9.go
- _test/if3.go
- _test/if4.go
- _test/if5.go
- _test/if6.go
- interp/cfg.go
In case of a constant condition, determined during control flow graph
analysis (cfg.go), test and alternate branch are considered useless and
cand be avoided completely during execution by setting the node tnext
field accordingly. This both fixes the issue #553 and possible variants,
and optimize the generated closures.
Fixes #553.
> fix: correct control flow graph for constant conditional statements

- _test/switch27.go
- _test/switch28.go
- _test/switch29.go
- _test/switch30.go
- _test/switch31.go
- _test/switch32.go
- _test/switch33.go
- interp/cfg.go
The CFG was not always correct for the last clause case, or
if the case body was empty. Several unit tests are added to
check all variants.
Fixes #560.
> fix: correct control flow graph for switch statement

- _test/interface29.go
- _test/interface30.go
- interp/run.go
As interpreter interface types are represented using valueInterface
struct, a different comparison routine to nil is required.
Fixes #561.
> fix: correct comparison of interface type to nil

- _test/if7.go
- interp/cfg.go
A boolean symbol must have a branch action when used in a conditional
expression. This was not the case if the symbol was enclosed in
parenthesis. A fixBranch function now detects parenthesis as well to
apply branch action as necessary.
Fixes #564.
> fix: correct branch action in parenthesis expression

- _test/issue-558.go
- _test/type20.go
- interp/run.go
The type checking feature is still missing for interpreter types, but
it can be used for binary types, so apply the reflect.Type.Implement
method to the asserted type.
Fixes #558.
> fix: checks that value implements a binary type in type assert

- _test/struct39.go
- _test/struct40.go
- interp/gta.go
- interp/type.go
Full analysis of mutually recursive structures requires several
GTA passes and the ability to cancel parsing until type is fully
defined. A recursive type completeness routine is added to better
catch direct or indirect recursive incomplete types.
Fixes #567.
> fix: incomplete type analysis

- _test/struct41.go
- _test/struct42.go
- _test/struct43.go
- _test/struct44.go
- interp/gta.go
- interp/type.go
As several GTA passes are required to handle forward declarations
and recursive types, make sure to update the type recursive status
in the type symbol, using scope to retrieve the symbol. The scope
was not always recorded at type creation. Fix that for dynamic
type creation which are potentially recursive.
Update refType() to return and interface{} in place of struct to
represent a recursive type using reflect.
Fixes #570.
> fix: better handling of recursive types and forward declarations

- interp/run.go
Allow method search on interperter struct pointer, in addition to struct.
Tested on a separate benchmark.
> fix: method search on struct pointer in interface wrapper

- interp/run.go
- interp/type.go
Add referTo and isRecursive type methods to assess a type
recursive status. Use the type path to avoid collisions
with same type name in different packages.
> fix: remove ambiguities in recursive type processing

- _test/struct45.go
- interp/type.go
On a struct pointer, it is necessary to dereference the struct
before iterating on its fields.
Fixes #575.
> fix: lookup embededded field on struct pointer

- _test/chan9.go
- _test/select4.go
- _test/select5.go
- _test/select6.go
- _test/select7.go
- _test/select8.go
- _test/select9.go
- interp/cfg.go
- interp/run.go
- interp/type.go
Receive channel in comm clause of select statements were only supported
for channel variables. Now channel init actions, for example to access
a channel struct field, are properly chained prior to invoke the select
operation. In addition, verify that the receive operation is on a
channel type data.
Fixes #577.
> fix: correct control flow graph for select blocks

- _test/composite8.go
- interp/run.go
When using reflect.Set() to assign a struct object to a variable, all
data is duplicated, but the underlying struct address in destination is
not affected, which is different of allocating a new struct.  The right
behaviour is to set directly the reflect.Value in the frame, without
using Set.
Fixes #579.
> fix: assign composite literal by reference

- _test/interface31.go
- _test/interface32.go
- _test/interface33.go
- _test/interface34.go
- _test/interface35.go
- interp/run.go
- interp/type.go
Interface values must be wrapped in valueInterface struct. This was
missing for composite literals. Also make sure to use frameType
method instead of TypeOf to get the correct reflect.Type representation.
Fixes #581.
> fix: correct handling of interface types in composite literals

- _test/not0.go
- _test/not1.go
- interp/ast.go
- interp/cfg.go
The branch condition was not always set or propagated in presence
of parenthesis expressions. Add a setFNext function to fix that.
Fixes #571.
> fix: correct branch control flow graph for parenthesis expressions

- _test/num0.go
- _test/op4.go
- _test/op5.go
- interp/ast.go
- interp/cfg.go
The conversion should occur only for certain arithmetic operators.
Also fixes the remain operator type checks.
Fixes #568.
> fix: do not convert literal float to int at parse

- _test/type21.go
- interp/cfg.go
> fix: correct type assertion for bin func types

- _test/map24.go
- _test/map25.go
- interp/cfg.go
- interp/run.go
- interp/value.go
Interface representation requires a valueInterface wrapper. Make
sure to wrap interface objects set by runtime functions (unaware of
the wrapper) when accessing map values.
Fixes #589.
> fix: handling values in map of interfaces

- _test/type22.go
- interp/gta.go
Populate the node field in the alias type creation so type can be
parsed again later when dependency is complete.
Fixes #592.
> fix: handle forward declaration for aliased type

- _test/interface36.go
- interp/type.go
Do not modify the complete state field of type before the end of
parsing. Capture the sub-fields complete state in a local var if
necessary. This is the same algorithm as for recursive struct.
Fixes #594.
> fix: parsing of recursive interface types

- _test/time12.go
- interp/type.go
Do not attempt to get the number of return args if the value
does not refer to a function, but a type.
Fixes #597.
> fix: handle type conversion from pre-compiled types.

- _test/select10.go
- _test/select11.go
- interp/cfg.go
- interp/run.go
The default comm clause, allowing to unblock select, was not correctly
implemented.
Fixes #599.
> fix: handle default comm clause in select

- _test/append0.go
- _test/cap0.go
- _test/complex4.go
- _test/copy2.go
- _test/fun14.go
- _test/imag0.go
- _test/len0.go
- _test/make0.go
- _test/make1.go
- _test/new2.go
- _test/real0.go
- interp/ast.go
- interp/cfg.go
- interp/run.go
- interp/value.go
Avoid duplication of func call output in frame, when function is
called from a return statement.
Handle the conversion of func outputs to interface if necessary,
with more changes to come.
Improve internal code comments.
Improve test coverage.
Fixes #607
> fix: improve handling of function return values

- _test/fun15.go
- _test/fun16.go
- _test/fun17.go
- _test/fun18.go
- _test/map26.go
- interp/run.go
- interp/type.go
As a followup of #613, make sure to wrap values returned by a function
call to a valueInterface, wether for assignment or return.
Fixes #614.
> fix: improving handling of functions returning interfaces

- _test/switch34.go
- interp/cfg.go
- interp/run.go
- interp/type.go
Complete generation of unique type id, to avoid false detection of
duplicate case. Fix the control flow graph at exit of last case clause.
Handle a nil interface value when testing for type.
Fixes #606.
> fix: improve switch and type switch statement processing

- _test/bin5.go
- _test/fun14.go
- _test/new2.go
- _test/struct37.go
- _test/struct45.go
- _test/type22.go
- interp/run.go
The method resolution can also be attempted directly on the
passed value.
While here, fix some expected test outputs.
Fixes #609.
> fix: improve generation of interface wrapper

- cmd/yaegi/yaegi.go
- cmd/yaegi/yaegi_test.go
- interp/interp.go
In REPL mode, pre-import all used pre-compiled binary packages,
except those having default name collisions (`crypto/rand`, `math/rand`).
Also enable REPL mode for yaegi script files (starting with `#!`).
Improve the yaegi doc to clarify differences between file mode and
REPL mode.
This change allows the following code to be a valid executable script:
```
#!/usr/bin/env yaegi
helloHandler := func(w http.ResponseWriter, req *http.Request) {
io.WriteString(w, "Hello, world!\n")
}
http.HandleFunc("/hello", helloHandler)
log.Fatal(http.ListenAndServe(":8080", nil))
```
Or to execute a one-liner such as:
```
$ yaegi -e 'println(reflect.TypeOf(fmt.Printf))'
```
This change has no impact on the default file mode (pure Go files),
or on the interp library.
> feature: pre-import used packages in REPL mode.

- _test/interface37.go
- interp/run.go
The wrapping of result in valueInterface is necessary only if
the source type is not already an interfaceT.
Fixes #623
> fix: correct assign from function returning an interface value

- _test/fun19.go
- _test/fun20.go
- interp/cfg.go
- interp/run.go
The frame index of returned values was incorrect in the case of a
function returning multiple outputs, called from a return statement.
Fixes #626.
> fix: improve setting results in multiple output functions

- _test/map27.go
- interp/cfg.go
- interp/type.go
The map entry detection routine was skipping map created in
runtime.
Fixes #624.
> fix: assign an element in a map from runtime

- .travis.yml
- _test/const12.go
- interp/cfg.go
- interp/interp_test.go
Remove the spurious constraint that a constant must be untyped
when testing for arithmetic properties.
Fixes #631.
> fix: compute numeral constant on typed objects

- _test/map28.go
- interp/cfg.go
The map range iterator was not initialized correctly for values
originating from runtime.
Fixes #641.
> fix: correct iterator in map range on binary values

- _test/interface38.go
- _test/interface39.go
- _test/interface40.go
- _test/interface41.go
- interp/cfg.go
- interp/run.go
If a value is assigned to, or returned as, a binary interface,
then use the interface wrapper generator to convert the value
accordingly.
Fixes #630.
> fix: use interface wrappers to expose interface values to runtime

- _test/switch35.go
- _test/switch36.go
- _test/switch37.go
- interp/cfg.go
The CFG was wrong in presence of an empty last clause.
Fixes #634.
> fix: handle empty clause in switch if statement

- cmd/yaegi/yaegi.go
- interp/dot.go
- interp/interp.go
- interp/src.go
As dotty does not seem to be readily available on MacOS, this PR extends
the ability to debug with dot, through the new YAEGI_DOT_CMD env var,
which allows one to specify the command to process the generated dot
graphs.
For example, to print the AST to svg:
YAEGI_AST_DOT=1 YAEGI_DOT_CMD='dot -Tsvg -ofoo.svg' yaegi ./foo.go
If any of YAEGI_AST_DOT or YAEGI_CFG_DOT is set, but YAEGI_DOT_CMD is
not defined, the default is to write to a .dot file next to the Go
source file.
> interp: extend dot debugging

- _test/baz-bat/baz-bat.go
- _test/import9.go
- interp/gta.go
- interp/src.go
This PR changes the naming of symbols from `importSrc` to use the package name. This handles cases where the package naming is not conventional.
Fixes #648
> Fix import source symbol package

- _test/recover2.go
- interp/run.go
In the nil case for `recover` setting any value does not equate to nil. Doing nothing seems to do the trick. As part of the test I have ensured it overrides any existing value in the variable.
Fixes #659
> fix: nil recover case

- _test/interface42.go
- interp/cfg.go
When an empty interface conversion was done, a panic was called due to the interface node type being nil. This handles this case.
Fixes #649
> fix: handle empty interface conversion

- _test/composite10.go
- _test/composite9.go
- interp/cfg.go
In the case of a call expression (make) in a composite literal expression, the node type is not correct, rather the call expression needs the actual type it will return.
Fixes #651
> fix: composite literal child types for call expressions

- _test/range7.go
- interp/scope.go
When ranging a channel from a function return, the return was not detected as a chan type. This attempts to fix this.
It is possible this needs to come out of the scope `rangeChanType` function and rather be part of `cfg.go`?
Fixes #667
> fix: handle range on chan function return

- _test/variadic7.go
- interp/ast.go
- interp/cfg.go
- interp/run.go
- interp/value.go
While variable expansion is not an issue in interpreter calls, in binary calls they need to be handled, otherwise the sees the expanded variable only. This introduces `aCallSlice` action when the `callExpr` has an ellipsis. As some code checks for `aCall` an `isCall` function is also added to be used in these cases.
Fixes #675
> fix: handle call ellipsis

- .travis.yml
- cmd/yaegi/yaegi_test.go
On my local machine, the 100 ms timeout in TestYaegiCmdCancel is not
enough to make the test pass.
So instead of hardcoding it to a larger
value, this PR adds the same kind of technique as is used in Traefik to
make the timeouts longer when they are run on the CI. Which allows me to
make the test pass on my local machine as well, by forcing the CI env
variable to true.
> Travis: apply timeout multiplier on CI

- _test/select12.go
- interp/cfg.go
The CFG was wrong for select send comm clauses. If an init operation
on channel was required (like a derefence, index operation, ...) it
was skipped. The bug was invisible in case of a local var channel.
A send channel init operation consist to prepare both the data to
send (right subtree of send AST) and the channel itself (left
subtree of send AST). All channel init operation must be performed
prior to call select.
Fixes #647.
> fix: perform send channel action for select

- _test/type23.go
- _test/type24.go
- interp/run.go
Type assertions need to do type validations before setting the values. Case 2 has been left intentionally and will make up its own PR, as I have no idea how to do the type assertion on it yet.
Fixes #682
> fix: type assertion of non-matching types

- interp/src.go
- interp/src_test.go
Fixes minor issue with importing a non-existent package where a part is the current package name.
Fixes #689
> fix: import non-existant package

- _test/variadic8.go
- interp/type.go
A refType function should be marked as variadic if it is.
Fixes #697
> fix: make reftype func variadic

- _test/unsafe5.go
- interp/hooks.go
- interp/interp.go
- interp/run.go
- stdlib/unsafe/unsafe.go
This adds `Sizeof` and `Alignof` to `unsafe`. Without access to the `node`, I dont see a way to add `Offsetof`, so it is left out for now.
The hook logic was also moved out of the interpreter, to keep it a little cleaner. This should also make any further extensions easier to fit in without changes to the interpreter code.
> feature: add Sizeof and Alignof to unsafe

- Makefile
- stdlib/unsafe/unsafe.go
It turns out there is a go pragma to turn off pointer checks. This is preferable to turning them off completely.
> fix: use pragma for ptr checks

- _test/chan10.go
- _test/range9.go
- interp/ast.go
- interp/cfg.go
- interp/interp_consistent_test.go
- interp/scope.go
- interp/type.go
This PR makes yaegi aware of receive and send types. 
It fixes  #701 which was caused by Yaegi considering [all channels to be bidirectional](https://github.com/containous/yaegi/blob/8365f687e784cb07febc382f68e891a90c00ad0d/interp/type.go#L1118).
In case of a binary call like `time.Tick`, the returned channel can actually be a receive channel and in that case we will try to assign it to a bidirectional channel, causing a panic.
To fix that, I made the AST aware of two new kinds `chanTypeRecv` and `chanTypeSend` then added two new type categories `chanSendT` and `chanRecvT`, so we can instantiate the channel values with the right direction.
Hope this helps.
Thanks @nrwiersma for the help !
> Handle Receive and Send channels

- _test/defer5.go
- _test/defer6.go
- _test/defer7.go
- _test/defer8.go
- _test/defer9.go
- interp/run.go
The only builtins that make sense in a standalone defer are `println` and `print`. Rather than complicating the builtin calling architecture, these functions themselves should handle defers. Should another case come up for defers with builtins, this solution can be rethought.
Fixes #655
> fix: handle defer in builtins

- _test/assign13.go
- interp/cfg.go
- interp/run.go
Map index assignments should not be optimized, so they can be set correctly. Further `callBin` should let `assign` optimize `aAssign`, and not try handle it itself.
Fixes #686
> fix: dont optimize map index assigns

- _test/assign14.go
- interp/cfg.go
When operations write their result to a non-local frame, the node
level field must be set accordingly, otherwise they attempt to write
in the wrong frame.
Fixes #730.
> fix: set frame level in destination nodes to avoid memory corruption

- _test/struct23.go
- _test/struct49.go
- _test/struct50.go
- _test/struct51.go
- _test/struct52.go
- interp/cfg.go
- interp/run.go
- interp/type.go
- interp/value.go
Nested recursion brings about a problem of different reflect types for each struct. To align the reflect types and be able to handle recursive conversions, all intermediate structs should also have an `interface{}` reflect type. It is also possible that the recursive type can have an arbitrary depth, making handling this conversion on a case by case bases impractical if not impossible. A more generic approach has been taken to handle this more gracefully.
Due to the lack on interface wrapper at this point, the only way to dereference a `[]interface{}` in a writable form is to use `reflect.NewAt` with `unsafe`. The inclusion of `unsafe` is not idea, but all other methods have consequences that effect other parts. This change should be considered temporary until another work around can be …
> feature: handle nested recursion

- _test/variadic9.go
- interp/run.go
Interface conversions were not handled in the variadic case in `call` and the unwrap was not handled in `callBin`. This fixes that.
Fixes #720
> fix: variadic interface conversion in call/callBin

- _test/issue-735.go
- _test/time13.go
- interp/run.go
In all situations where the results are set directly
into the frame, and not using a value helper, the right level of
indirections must be applied, otherwise we may end-up writing
in the wrong frame (the local one, instead of a caller or global).
Fixes #735.
> fix: avoid memory errors by handling frame indirections

- interp/interp_eval_test.go
- interp/run.go
`genFunctionWrapper` expects all function params to be of type `*node`. When calling from `Eval` this is not handled, so a node needs to be generated to call the given function.
I am unsure of the name `genFunctionNode`, suggestions on this are welcome.
Fixes #468
> fix: handle Func Value in genFunctionWrapper params

- _test/comp2.go
- internal/genop/genop.go
- interp/cfg.go
- interp/op.go
When checking equality with a const and non-const, the type of the const must be resolved. This is done as early as possible after the type check in the CFG. This also fixes a bug in the operations.
Fixes #744
> fix: a const, non-const equality check must convert

- _test/type25.go
- _test/type26.go
- interp/cfg.go
In a struct case in type assertion, if the source is a valueT, we still need to take the struct type to allow method and field resolution.
Fixes #746
> fix: assert switch type from valueT in struct case

- _test/struct53.go
- interp/type.go
Mark all visited types as such when walking down struct fields.
Fixes #750.
Updates #652.
> fix: avoid infinite loop when parsing recursive types

- _test/interface44.go
- interp/run.go
Due to the assignment optimisation for composite sparse, assigning to an interface must be handled in `doCompositeSparse`.
Fixes #748
> fix: handle interfaces in composite sparse

- _test/struct54.go
- interp/type.go
As we have to changed `defined` in `isRecursiveStruct` to remove potential infinite loops, we need to make a copy so it doesnt leak out to the actual defined.
Fixes #754
> fix: make a copy of defined before detecting recursivness

- _test/interface45.go
- interp/run.go
If the status is _, there is no storage allocated in frame, and
the status assign operation should be skipped.
Fixes #761.
> fix: type assert when status is _

- _test/const15.go
- interp/cfg.go
By returning early in case of incomplete type in CFG, we avoid
a panic, and let a chance to a new attempt after the missing
type has been parsed.
Fixes #763.
> fix: avoid a panic in CFG in case of incomplete type

- _test/var12.go
- _test/var13.go
- _test/var14.go
- _test/vars/first.go
- _test/vars/second.go
- interp/cfg.go
- interp/gta.go
- interp/interp.go
- interp/run.go
- interp/src.go
To conform to the global spec, we need to reorder global variables and execute them before running init nodes.
Fixes #756
Fixes #742
> fix: execute global variables in the correct order

- _test/init1.go
- interp/cfg.go
- interp/gta.go
- interp/interp_consistent_test.go
As per the Go spec, `init` functions never get declared and therefore can never be called.
Fixes #766
> fix: dont allow calling init

- _test/math2.go
- interp/cfg.go
As we have both constVal and untyped, they both need to be checked in the binaryExpr type check. This is a stop gap fix. The  type checking needs to be looked at again.
Fixes #768
> fix: deal with untyped in type check

- _test/issue-775.go
- interp/cfg.go
The range init AST execution was skipped, and range could work
only over variables or direct function calls. By setting the
start node to the start of init and not init itself, we ensure
that the init AST is always taken into account.
Fixes #775.
> fix: correct control flow graph for range init expression

- example/pkg/_pkg12/src/guthib.com/foo/main.go
- example/pkg/_pkg12/src/guthib.com/foo/pkg/pkg.go
- example/pkg/_pkg12/src/guthib.com/foo/vendor/guthib.com/bar/bar.go
- example/pkg/pkg_test.go
- interp/src.go
- interp/src_test.go
- interp/testdata/src/github.com/foo/bar/baz/baz.go
- interp/testdata/src/github.com/foo/vendor/whatever/whatever.go
Namely, when the vendor dir is a sibling (or an uncle) relative to the
current pkg
Fixes #758
> interp: support yet another vendoring case

- _test/issue-782.go
- interp/run.go
One must use `vInt()` to handle all valid number cases.
Fixes #782.
> fix: correct conversion to int in slice index expressions.

- _test/issue-784.go
- interp/value.go
> fix: correct range on arrays of interface objects

- interp/cfg.go
- interp/value.go
This change fixes a nil pointer dereference regression introduced by
PR #787 which caused a traefik plugin to fail.
> fix: regression on range following #787

- _test/interface46.go
- interp/run.go
Fix #787 changes how interfaces are set on a struct (compositeSparce). This change however makes calling the interface panic. 
This PR reverts part of the change in #787 and adds a test to ensure it does not break again.
> fix: interface call regression from #787

- _test/math3.go
- interp/cfg.go
- interp/interp_eval_test.go
- interp/run.go
- interp/typecheck.go
- interp/value.go
This adds type checking to both `IndexExpr` and `CompositeLitExpr` as well as handling any required constant type conversion.
This includes a change to the type propagation to the children of a composite literal. Previously in most cases the composite literal type was propagated to its children. This does not work with type checking as the actual child type is needed.
> feat: add index and composite literal type checking

- _test/struct55.go
- interp/cfg.go
- interp/run.go
In the case of a pointer or alias composite literal expression, `compositeGenerator` changes the type to remove the pointer or alias. This causes a nested composite literal to have the wrong type.
Instead of changing the node type, the removal of the pointer or alias is moved to the runtime, allowing the node type to remain unchanged. This fixes potential issues in the type checking.
> fix: composite literal type check

- interp/run.go
In a couple of occurences, tests with enabled race detector exposed
some concurrent accesses to the cancelation callback used in select and
channel operations send and recv for EvalWithContext. This change ensure
that all accesses to this object are protected by mutex.
Fixes #815.
> fix: add mutual exclusion locks for cancelable select

- interp/cfg.go
- interp/interp_eval_test.go
- interp/typecheck.go
This adds type checking to SliceExpr as well as handling any required constant type conversion.
It should be noted that the check that `high` and `max` are not nil in a 3-index slice has been left out as this check is handled before type checking. Tests have been included for these cases.
> feat: add slice expression type checking

- _test/method35.go
- interp/cfg.go
- interp/run.go
- interp/type.go
- interp/typecheck.go
This adds type checking to TypeAssertExpr. In order to allow for this, method types now have a receiver type in both reflect and native cases.
> feat: add type assertion expression type checking

- interp/cfg.go
- interp/interp_eval_test.go
- interp/typecheck.go
This adds type checking to StarExpr. This also fixes a bug in assignment where the symbol type was updated but not the scope type associated with it.
> feat: add star expression type checking

- interp/interp_eval_test.go
- interp/type.go
When determining the size of an array and a symbol is found, the symbol must be a const for the type to be valid. 
While it makes sense for this check to be done in type checking, the type can be determined by GTA which would then fail. For now this check is done when getting the node type.
Fixes #825
> fix: check array size symbol kind

- interp/interp.go
The input scanning is now performed in a sub goroutine and
the interrupt is listened in another goroutine, either to cancel Eval
or to cancel the current line scan.
Entering a '\n' after a 'Ctrl-C` to get the prompt is
not necessary anymore.
> feature: improve handling of interrupt signal in REPL

- interp/ast.go
- interp/interp.go
- interp/interp_eval_test.go
In interactive mode, a line starting with the "func" keyword is usually
"wrapped", by prepending to it a "package main" statement, to make it
a valid piece of Go source code.
However, when the line is actually an anonymous function call, such as:
```
func() { println(3) }()
```
then this wrapping is not enough, as this is not valid Go in the global
context. Therefore, this kind of of expression must also be wrapped
inside a main func (as is the default case for most REPL inputs).
Since the detection and handling of such a case turned out to be quite
unelegant, this PR instead introduces a retrying phase when a parsing
error occurs for a particular class of cases. That is to say, when a
"func expression" wrapped in a main package fails to be parsed, it is
then wrapped in a main func before …
> REPL: retry with full wrapping for anonymous func calls

- _test/redeclaration-global5.go
- interp/ast.go
- interp/cfg.go
- interp/gta.go
- interp/interp_eval_test.go
The Go parser is able to detect some (but not all) (re-)declaration errors,
if the DeclarationErrors flag is enabled, which was not done so far.
This PR therefore enables that flag, which allows the removal of some of
the now unneeded code that was recently added to support redeclarations.
Fixes #811
> interp: enable declaration errors detection at parsing time

- interp/interp_eval_test.go
When running TestEvalScanner with -race=true, one can observe a data race such as:
```
WARNING: DATA RACE
Read at 0x0000029f3d68 by goroutine 52:
github.com/containous/yaegi/interp.(*itype).defaultType()
/Users/mpl/src/github.com/containous/yaegi/interp/type.go:1466 +0x572
...
github.com/containous/yaegi/interp.(*Interpreter).EvalWithContext.func1()
/Users/mpl/src/github.com/containous/yaegi/interp/interp.go:501 +0xf0
Previous write at 0x0000029f3d68 by goroutine 43:
github.com/containous/yaegi/interp.(*itype).refType()
/Users/mpl/src/github.com/containous/yaegi/interp/type.go:1419 +0x854
github.com/containous/yaegi/interp.(*itype).TypeOf()
/Users/mpl/src/github.com/containous/yaegi/interp/type.go:1427 +0xa6
...
github.com/containous/yaegi/interp.(*Interpreter).EvalWithContext.func1() …
```
> TestEvalScanner: "fix" data race

- _test/eval0.go
- _test/inception.go
- cmd/yaegi/run.go
- cmd/yaegi/yaegi_test.go
- example/pkg/pkg_test.go
- interp/interp.go
- interp/interp_eval_test.go
- interp/interp_file_test.go
- interp/run.go
The goal is to provide greater control of input, output and error
streams of the interpreter. It is now possible to specify those
as options when creating a new interpreter. The provided values
are propagated to relevant stdlib symbols (i.e fmt.Print, etc).
Care is taken to not update the global variables os.Stdout, os.Stdin
and os.Stderr, as to not interfere with the host process.
The REPL function is now simplified. The deprecated version is removed.
The tests are updated to take advantage of the simplified access
to the interpreter output and errors.
Fixes #752.
> feat: configure stdin, stdout and stderr per interpreter

- interp/interp.go
- interp/interp_eval_test.go
- interp/testdata/concurrent/hello1.go
- interp/testdata/concurrent/hello2.go
- interp/type.go
This change fixes two distinct data races:
1) some global vars of type *itype of the interp package are actually
mutated during the lifecycle of an Interpreter. Even worse: if more than
one Interpreter instance are created and used at a given time, they are
actually racing each other for these global vars.
Therefore, this change replaces these global vars with generator
functions that create the needed type on the fly.
2) the symbols given as argument of Interpreter.Use were directly copied
as reference (since they're maps) when mapped inside an Interpreter
instance. Since the usual case is to give the symbols from the stdlib
package, it means when the interpreter mutates its own symbols in
fixStdio, it would actually mutate the corresponding global vars of the
stdlib package. Again, this …
> interp: fix data races

- _test/cli6.go
- interp/type.go
When searching for a binary method on structures, look up on embedded
fields first, otherwise the resulting index is incorrect, as
reflect.Type.MethodByName succeeds also on container struct.
Fixes #834.
> fix: correct index for embedded binary method receiver

- _test/cli4.go
- _test/cli5.go
- interp/run.go
Struct fields of type interface must be converted in wrapper
values to be reachable by the runtime. Call genInterfaceWrapper
on such values.
Fixes #832.
> fix: handle interface fields in literal composite structs

- interp/interp_eval_test.go
- interp/run.go
- interp/testdata/concurrent/composite/composite_lit.go
- interp/testdata/concurrent/composite/composite_sparse.go
- interp/type.go
This change fixes two data races related to composite literal creation.
The first one isn't controversial as it is just about initializing the
variable that contains the values in the right place, i.e. within the
n.exec, so that this variable is local to each potential goroutine,
instead of being racily shared by all goroutines.
The second one is more worrying, i.e. having to protect the node typ
with a mutex, because a call to func (t *itype) refType actually
modifies the itype itself, which means it is not concurrent safe.
The change seems to work, and does not seem to introduce regression, but
it is still a concern as it probably is a sign that more similar
guarding has to be done in several other places.
> interp: fix data race for composite literal creation

- _test/m2/m2_test.go
- _test/variadic10.go
- interp/run.go
The computation of receiver offset for variadic methods was incorrect.
The logic to apply or not the receiver offset for variadic was incorrect
too. Receiver offset must not be added for variadic arguments beyond
the minimum number of arguments.
Fixes #858
> fix: correct access to parameter type for variadic binary methods

- _test/composite12.go
- _test/composite13.go
- _test/composite8bis.go
- interp/cfg.go
- interp/interp.go
- interp/run.go
Also, there is an optimisation that used to take place when the RHS of
an assignment is a struct literal. That optimisation avoids some
allocation by "instructing" that whatever we want to write for the frame
of the RHS gets directly written to the frame of the LHS.
But it just so happens that we're doing this incorrectly when the LHS is
a struct field (or probably for any other kind of getIndex AST
action). Therefore this PR also disables the optimisation when the LHS
is a getIndex.
Fixes #851
Fixes #854
> interp: refactor doComposite cases

- cmd/yaegi/run.go
`flag.Parse()` fails with a panic when run using `yaegi run` as there are an unexpected number of args. It expects the first arg to be the application name. In the case of yaegi it makes sense that this is the script name. 
Fixes #868
> fix: yaegi os.Args should contain the script name

- _test/struct58.go
- interp/type.go
Struct tags were forgotten in the conversion of constant values. They need to be converted from constant values before being assigned.
Fixes #873
> fix: convert struct tags properly

- interp/interp_eval_test.go
When testing concurrent eval, more valid output combinations
are possible, specially intermixed lines.
This would fix wrong CI builds such as
https://travis-ci.com/github/traefik/yaegi/jobs/391714212
> fix: concurrent eval test

- README.md
Replacing playground link in doc, the previous code imported containous instead of traefik.
> fix: replace playground link in docs

- _test/const17.go
- cmd/yaegi/yaegi.go
- internal/cmd/genop/genop.go
- interp/interp.go
- interp/interp_eval_test.go
- interp/op.go
- interp/typecheck.go
When working with an untyped const expression involving a division, if
the default type of the result should be an int (for example because the
default types of all the operands are ints as well), then we should make
sure that the operation that is applied is indeed an integer division,
and that the type of the result is not a float.
This is achieved by using the QUO_ASSIGN operator, instead of the QUO
operator.
This should fix several problems lurking around, and it notably fixes
one of the visible consequences, which is a systematic panic when using
the REPL as a "calculator".
This incidentally also allows us to revert what was done in
5dfc3b86dc7753b035343261339663dd78520412 since it now turns out it was
just a hack to fix one of the symptoms.
Fixes #864
> interp: apply integer division when appropriate

- _test/binstruct_slice0.go
- interp/cfg.go
- interp/run.go
When the type is implicit, the first element in the list of children is
not the type of the composite literal, but it is one of the actual
children, so it should not be discarded.
Fixes #862
> interp: fix implicit type for bin composite lit case

- _test/binstruct_ptr_map0.go
- _test/binstruct_ptr_slice0.go
- interp/cfg.go
- interp/run.go
Also fix same case for implicit-type maps of etc.
Fixes #883
> interp: support implicit-type slice of pointers of struct composite literal

- README.md
- cmd/yaegi/run.go
- cmd/yaegi/yaegi.go
- interp/hooks.go
- interp/interp.go
- interp/run.go
- interp/src.go
- interp/type.go
Since the introduction of restricted stdlib and syscall symbols, the
capability of yaegi to interpret itself was broken.
The use of unrestricted symbols is now also controlled by environment
variables, to allow propagation accross nested interpreters.
The interpreter Panic symbol was not wrapped, this is fixed now.
the import path resolution was failing if the working directory was
outside of GOPATH.
The documentation and readme have been ajusted.
Fixes #890.
> fix: allow yaegi command to interpret itself

- Makefile
- _test/select14.go
- interp/cfg.go
- interp/run.go
- interp/type.go
There was several issues:
- access to field on pointer to struct from runtime: fix in
lookupBinField
- assign operation was skipped when performed in a comm clause
- the direction of comm clause was wrong if a channel send operation was
performed in a body of a receive comm clause
Fixes #884.
> fix: behavior of select and time ticker

- .travis.yml
- Makefile
- cmd/yaegi/help.go
- cmd/yaegi/yaegi.go
A version sub-command is implemented.
A local install target is added to Makefile, to set version from git at build.
Fixes #840.
> feature: provide a version sub-command

- _test/fun23.go
- cmd/yaegi/run.go
- cmd/yaegi/yaegi.go
- interp/cfg.go
- interp/interp_consistent_test.go
Also fix error ouptut in the run command to avoid displaying twice
the same error.
Fixes #819.
> fix: detect a wrong number of arguments at return

- cmd/yaegi/test.go
- interp/interp.go
Often enough when debugging, one does not know exactly what argument
should be given to Symbols, as it's not always clear in which
scope/namespace the symbol one is looking for is stored in.
Therefore, this change enables the Symbols method to now take the empty
string as an argument, which results in all the known symbols to be
returned (keyed by import path).
As a consequence, when an non-empty argument is given, the returned
result should be similar to what we had before, except it is now
returned as the sole entry of an encompassing map.
In addition, the "binary" symbols (i.e. the ones ingested through a
Use call), are now also taken into account.
> interp: API change for Symbols method

- interp/typecheck.go
added `kind` to log
```
invalid operation: cannot take address of []github.com/rsteube/traefik-plugin-brotli/vendor/github.com/andybalholm/brotli.huffmanTree [kind: sliceExpr]
```
> interp: added kind to log for typecheck

- _test/fun24.go
- _test/fun25.go
- interp/cfg.go
- interp/interp_consistent_test.go
- interp/type.go
The assignable check used to be too strict as it lacked the property that
if an untyped const can be represented as a T, then it is assignable to T.
And we can now use that fixed check to add a missing check: in a return
statement, we now make sure that any of the returned elements are
assignable to what the signature tells us they should be.
> interp: fix assignable check

- _test/a44.go
- interp/type.go
In type.go, the symbol lookup on constant id was not performed. Handle
the ident kind explicitely to allow that.
Fixes #911.
> interp: fix array size definition in case of forward declared constant

- _test/slice.go
- interp/typecheck.go
In typecheck.go, type check was failing for expressions like `[2]int{0, 1}[0:]`.
```
cannot slice type [2]int
```
Fixes #914 .
> interp: add indexExpr check for reflect.Array

- _test/assign16.go
- _test/select1.go
- interp/cfg.go
- interp/interp_eval_test.go
- interp/typecheck.go
Type checking on shift operands was failing for untyped variable values.
Fix propagation of type in assignment. Optimize assignment of arithmetic
operations on variables by skipping the assign and writing directly to
destination frame value in the operator function.
Skip some slow tests when given -short test option.
Fixes #917.
> interp: fix type in assign of shift operations

- _test/const21.go
- interp/run.go
The case of a constant arithmetic expression being of float kind because
of quotient was not handled correctly. Simplify constant extraction to
reflect.Value first, then conversion to target type, and let reflect Convert
method panic if conversion is not valid.
Fixes #920.
> interp: fix type conversion for constant expressions

- _test/for15.go
- interp/ast.go
- interp/cfg.go
Add a for statement variant for the case of a "for" with an init, no
condition and no post-increment.
Fixes #933.
> interp: fix incorrect infinite loop on for statement

- interp/cfg.go
- interp/interp_eval_test.go
- interp/run.go
- interp/typecheck.go
A non-constant shift expression can be untyped, requiring to apply a
type from inherited context. This change insures that such context is
propagated during CFG pre-order walk, to be used if necessary.
Fixes #927.
> interp: resolve type for untyped shift expressions

- _test/convert0.go
- interp/run.go
Interpreter function types are represented internally by the AST node
of their definition. The conversion operation creates a new node with
the type field pointing to the target type.
Fixes #936.
> interp: implement conversion for interpreter function types

- _test/for16.go
- interp/ast.go
- interp/cfg.go
Refactor `for` variants for clarity. Ensure all possible 8 combinations
are covered.
Fixes #942.
> interp: fix CFG in case of for loop with empty init and cond

- example/pkg/_pkg13/src/guthib.com/foo/bar/main.go
- example/pkg/_pkg13/src/guthib.com/foo/bar/vendor/guthib.com/bat/baz/baz.go
- example/pkg/pkg_test.go
- interp/gta.go
When running GTA, the type `path` was set to `rpath`. This equates to the package path (`github.com/traefik/yaegi`) in most cases. In the vendored case the `rpath` is the sub package path `something/vendor/github.com/traefik/yaegi` causing issues in typecheck and likely further down the line. By using the `importPath` it makes this consistent.
**Note:** I have no clue how to test this decently. I am open to options here.
Potentially Fixes #916
> fix: use the import path for types

- interp/interp_eval_test.go
- interp/value.go
The function vUint, used to get the unsigned integer value of a value,
variable (frame) or constant, was broken for constant.Value expression.
Fixes #948.
> interp: fix getting unsigned constant value

- interp/run.go
in `callBin`, call arguments are converted to the corresponding
parameter type. In a case of an interface, the original concrete type
should be preserved instead, and only wrapped to an interface type for
internal interpreter types, as runtime values should already implement the
interface.
This change removes the interface wrapping when parameter is a runtime
value (valueT or ptrT to valueT).
This removes some overhead when handling runtime values, and keep a
similar behavior between interpreted and pre-compiled code. For
example, `io.Copy` preserves its internal optimisations when passed a
`bytes.Buffer`.
> interp: avoid useless interface wrapping

- _test/time14.go
- interp/cfg.go
- interp/scope.go
Perform function declaration type check from the upper level scope (the scope where the
function is declared), to avoid possible collisions of local variables with package names.
Fixes #957.
> interp: fix type check on function signature

- _test/fun26.go
- interp/cfg.go
Use node action to better discriminate between function call and type
conversion which have the same pattern at AST level.
Fixes #960.
> fix: do not confuse function call with type conversion

- cmd/yaegi/test.go
Because this is what `go test` does, and some packages depend on that,
for example `github.com/jjcollinge/servicefabric`.
> test: chdir to package directory prior to launch tests

- _test/time15.go
- interp/cfg.go
- interp/gta.go
- interp/type.go
In aliased type declarations, when the target type was imported from
an external package rather than declared locally, the aliased type was
overwritten by target, loosing ability to lookup methods on the aliased
type. Aliasing on imported types is now properly detected and handled.
Fixes #971.
> interp: fix method lookup on aliased types

- _test/assert0.go
- _test/assert1.go
- interp/run.go
The long-form (with comma-ok) ones were already fixed but the short-form
ones were not because they were in a completely different code path.
This PR also refactors the code so that both short-form and long-form
are now merged in the same function.
N.B: even though most (all?) cases seem to now be supported, one of them
still yields a result that does not satisfy reflect's Implements method
yet. It does not prevent the resulting assertion to be usable though.
N.B2: the code path for the third-form (_, ok) hasn't been fixed and/or
refactored yet.
Fixes #919
> interp: fix short-form type assertions

- interp/interp_eval_test.go
- interp/typecheck.go
The type check was generating false negatives. A correct test to check the
adressable status of an array is more complex to implement, and will
be done later.
Fixes #973.
> interp: remove incorrect type check on array object

- _test/assert0.go
- _test/assert1.go
- interp/cfg.go
- interp/run.go
typeAssertStatus deals with the 3rd form of type assertion ("_, ok"), for
when one does not care about the result of the assertion itself.
Some cases for it, which are already fixed for the two other forms of
type assertions, had not been fixed for this form yet.
Therefore, this change fixes such cases for this form, while integrating
typeAssertStatus to the same code path as for the two other forms.
> interp: fix and refactor typeAssertStatus in

- _test/interface47.go
- interp/cfg.go
- interp/run.go
- interp/value.go
The interpreter interface type was replaced by a reflect.Value in
objects passed or return to function wrappers, losing the ability
to retrieve methods.
The valueInterface is now preserved, and correctly accessed if
wrapped multiple times.
Fixes #977.
> interp: fix handling interface types in wrapped functions

- _test/issue-993.go
- _test/var15.go
- interp/cfg.go
- interp/gta.go
- interp/interp.go
- interp/run.go
- interp/scope.go
- interp/value.go
In some cases, the global character of a value was lost, leading to
undefined behaviour. Now a node level field of -1 means that the value
is global, and that it should be accessed from the root data frame.
Fixes #993.
> interp: fix memory handling of global values

- .goreleaser.yml
The release of v0.9.9 failed, due to
https://goreleaser.com/deprecations/#brewsgithub.
> chore: rename github to tap, following goreleaser deprecation notice

- _test/interface48.go
- _test/interface49.go
- interp/gta.go
- interp/type.go
An undefined type detection function has been added to better diagnose
incomplete type definitions. Implicit type names in interface or struct
declarations are now better handled. The incomplete status is not
fowarded to aliased type declarations to handle circular definitions.
Fixes #999 and #995. Improves #260 (goes farther, but still fails).
> interp: parse circular interface definitions

- _test/const22.go
- internal/cmd/genop/genop.go
- interp/op.go
Always attempt to obtain an integer constant value for operators
expecting so. It allows to use '/' in integer constant defintions,
instead of default big.Rat.
Fixes #1005
> interp: fix operators working on integer constants

- _test/issue-1007.go
- interp/type.go
If a struct contains several fields of the same temporary incomplete
type, it could be detected incorrectly as a recursive struct. Pass
a copy of defined types map to avoid this issue.
Fixes #1007.
> interp: fix detection of type recursivity

- _test/issue-981.go
- interp/cfg.go
The logic to trigger assigment optimizations has been refactored for
clarity, and to exclude assignments to map entries.
Fixes #981.
> interp: fix map assignment from arithmetic operations

- _test/struct59.go
- interp/type.go
Fix the logic to detect recursive struct types, which was giving a false positive.
We now use the local type name  as key in tracker map.
A non-regression test case is included (_test/struct49.go).
This completes #1008.
> interp: fix type recursivity detection

- _test/const23.go
- _test/const24.go
- interp/cfg.go
- interp/run.go
- interp/type.go
One builtin has been identified to be used for constant definition:
len(), with a constant string argument. Add support for this.
Fixes #1012.
> interp: allow early constant evaluation from builtin call

- _test/issue-1010.go
- interp/run.go
- interp/type.go
A channel can be used to interchange data with the pre-compiled
runtime and therefore objects impletementing interfaces must be
wrapped if necessary, using genInterfaceWrapper.
A similar treatment could be applied when sending interpreted
functions over a channel, to be provided in a new PR.
Fixes #1010.
> interp: fix sending object implementing an interface through channel

- _test/composite17.go
- interp/run.go
When passing a function reference as an interface in a composite binary map, the case should be handled to not take the value of the the node.
Related to #886
> fix: handle function references in composite bin map

- interp/cfg.go
- interp/interp_eval_test.go
When checking for untyped values, we can be sure at this stage that they must be a const value or already untyped. Checking for type string equality is no longer a good measure.
Fixes #1000
> fix: untyped check

- _test/issue-1022.go
- interp/run.go
A wrong logic was leading to panic in recover. Simplify the
workflow for clarity.
Fixes #1022.
> interp: fix nil value check in case of interface

- _test/time16.go
- interp/type.go
- interp/typecheck.go
The default type must be derived from the constant value when necessary,
otherwise the type check fails wrongly.
Fixes #1026.
> interp: fix default type for constants from runtime

- _test/interface50.go
- internal/cmd/genop/genop.go
- interp/op.go
- interp/run.go
This is a follow-up of #1017, generalizing the use of reflect.Set
method to set, and possibly overwrite, the concrete value of
interface objects all accross the implementation of operators.
Previous optimized implementation for non-interface objects is
preserved.
> interp: fix setting interface objects from operators

- interp/interp.go
- interp/run.go
As mentioned in #1030, when an Eval panic, it is print with `fmt.Println()` and not to the configured `interp.Options.Stderr`. According to https://github.com/traefik/yaegi/blob/master/interp/interp.go#L210, it should be removed in future version so I'm not sure if this pull request is necessary. However, it could fix the issue in the meanwhile.
Fixes #1030.
> Use fmt.Fprintln instead of fmt.Println in runCfg

- _test/closure10.go
- _test/closure11.go
- _test/closure12.go
- _test/closure9.go
- _test/select14.go
- cmd/yaegi/yaegi_test.go
- interp/cfg.go
- interp/interp.go
- interp/interp_eval_test.go
- interp/run.go
The first change forces a variable definition to reallocate a
new memory slot to avoid corrupting a previously defined one in
a loop block.
The second change ensures that the frame clone operations obtains
a copy of the original data slice, to preserve the original context
set in a loop.
Fixes #1035.
> interp: fix a memory management issue causing wrong closure context

- _test/method36.go
- interp/cfg.go
- interp/run.go
- interp/type.go
- interp/value.go
Functions in a struct fields are always wrapped (as potentially
used by the runtime), so generate a function wrapper also for
closure when assigned to a struct field.
When such a function is called from the interpreter, ensure that
interface arguments are also wrapped so method and receiver resolution
can be performed.
Fixes partially #1043.
> interp: fix closure in a struct field

- _test/issue-1052.go
- interp/cfg.go
> interp: do not skip use of tmp frame in multi-assign

- interp/gta.go
- interp/interp.go
This PR adds an interpreter option, `AllowRedeclaration`. If this option is set, `(*Interpreter).Eval` will allow package imports to be redeclared. That is, no error will be raised and the package symbol will be overwritten.
I would like to use Yaegi to power a Go notebook (VSCode extension), somewhat like Jupyter. A notebook can have multiple Go 'cells' which can be evaluated (using Yaegi). As much as is possible, evaluating cells should be idempotent - that is, evaluating a cell multiple times should have the same effect as evaluating it once, ideally. Cells that are not idempotent can degrade the user experience.
Specifically, Go files tend to declare all imports in a single block. In a notebook, I'd put all imports in a single block, in their own cell. When I decide I need to import …
> interp: allow redeclaration of imports

- _test/issue-1065.go
- interp/run.go
- interp/typecheck.go
> interp: fix append on variadic recursive struct

- .github/workflows/go-cross.yml
- interp/ast.go
- interp/cfg.go
- interp/interp_eval_test.go
This PR:
- Treats a `varDecl` within a block as a `defineStmt`
- More specifically, any `varDecl` with a grandparent that is *not* a `fileStmt`
- Adds an extra condition to the handler for implicit const assignment
- Adds a tests to cover the changes
- Closes #1071
> interp: treat var declaration within a block as a define statement

- interp/gta.go
- interp/interp_eval_test.go
If I execute the following:
```
I := interp.New(interp.Options{})
I.Eval(`x := 1`)
I.Eval(`x := "foobar"`)
```
I expect the second declaration to override the first. `var x string` will override the previous type, and redeclaring a type, function, const, etc will override it, but the `:=` operator will not.
Currently, the result is: `reflect.Set: value of type string is not assignable to type int`
> Allow colon-equal to override variable type

- interp/cfg.go
- interp/run.go
- interp/type.go
- interp/typecheck.go
Add missing `sliceT` type category for consistency. Remove
`sizedef` field in `itype` struct. Rename field `size` to `length`.
Clean the various hacks used to cope with the absence of `sliceT`.
> interp: refactor slice type management

- _test/unsafe5.go
- interp/cfg.go
- stdlib/unsafe/unsafe.go
Offsetof returns the offset of a field in a struct. It is computed
during parsing at CFG, due to the constraint of operating on a
struct selector expression.
With this function, the support of 'unsafe' package is now
complete in yaegi.
Fixes #1062.
> interp: implement unsafe.Offsetof

- _test/issue-1068.go
- interp/cfg.go
- interp/run.go
- interp/type.go
Avoid to test directly for a type category, as it may give wrong
results for aliased types, where the interesting category remains
masked.  Instead, use some property helpers, such as isFuncSrc,
isPtrSrc and isInterfaceSrc to check if a type is of source function,
source pointer or source interface respectively (versus runtime
defined function, pointer or interface).
Fixes #1068.
> interp: improve handling of aliased types

- interp/interp.go
The interpreter is exposed to itself through a "Self" var which
is set on "Use" of the interpreter package.
It allows meta-programming features, for example using "Eval" in
the current interpreter context, or enabling self-inspection
capabilities.
> interp: give a self to the interpreter

- cmd/yaegi/run.go
- interp/gta.go
- interp/interp.go
- interp/typecheck.go
This feature was already present, but part of REPL only.
It's now also possible to apply it when evaluating a string
(-e flag). Default package names collision handling is no
longer hard-coded.
With -e flag, the eval result is now printed if valid, allowing
simpler commands:
yaegi -e 'reflect.TypeOf(fmt.Printf)'
instead of:
yaegi -e 'println(reflect.TypeOf(fmt.Printf))'
Fixes #1084.
> interp: add ImportUsed method to pre-import compiled packages

- _test/issue-1091.go
- interp/cfg.go
- interp/run.go
In that case, direct propagation of result can not be attempted,
as the frame types will be different between the source and destination.
Disabling the optimisation and using The regular case involves an intermediate
frame entry, which enables the type conversion.
Fixes #1091.
> interp: fix return of function call involving a type conversion

- _test/issue-1088.go
- interp/cfg.go
- interp/run.go
In this range variant "for k, v := range aString", k must
be the byte position of the rune in the byte array, rather than
the index of the rune in the rune array.
Fixes #1088.
> interp: fix special range on string

- interp/interp.go
- interp/type.go
- interp/typecheck.go
Some binary method calls were wrongly rejected. There is still
some ambiguous cases as binary method signature may include or
not the receiver as first argument, depending on how the method
was resolved.
With this fix, `import "golang.org/x/net/html"` doesn't panic
anymore, but not all tests are passing yet, i.e.
`yaegi test golang.org/x/net/html` still has failures, to be
investigated.
Fixes #1107.
> interp: improve type check of binary methods

- interp/interp.go
- interp/interp_eval_test.go
- interp/interp_file_test.go
Use YAEGI_SPECIAL_STDIO env boolean to overwrite os.Stdxxx by
non file descriptors io.Writer / io.Reader interfaces. It is set
to true when testing to allow redirection to byte buffers.
The default behaviour is now to preserve the original concrete type
when sandboxing stdio, which maintains compatibility.
Fixes #1092.
> interp: sandbox to preserve type of os.Stdin os.Stdout and os.Stderr

- _test/issue-1101.go
- interp/cfg.go
- interp/type.go
In binary packages, constants are wrapped in constant.Values, to
support arbitrary precision. Their type must therefore be converted
back to a regular type at import.
Fixes #1101.
> interp: fix constant types from imported packages

- _test/method37.go
- interp/cfg.go
This case was missing in the selector expression processing.
Fixes #1083.
> interp: fix method lookup on pointers to binary types

- _test/map30.go
- interp/run.go
- interp/type.go
- interp/value.go
The case of assigning a binary function to a funcT object was
solved elsewhere. Factor the case in genDestValue to apply it
at multiple places.
Fixes #1100.
> interp: fix litteral map containing binary functions

- interp/src.go
> interp: fix relative import path detection on MS-Windows

- _test/ret8.go
- interp/cfg.go
De-optimize a use case to avoid skipping an assign operation with an implicit type assertion at function call return.
Fixes #1122.
> interp: fix assign of function call with implicit type assert.

- stdlib/unrestricted/unrestricted.go
This is fixing a regression introduced by #1102.
Fixes #1129.
> interp: fix use of unrestricted symbols

- _test/addr2.go
- _test/addr4.go
- _test/issue-1094.go
- _test/issue-1126.go
- interp/cfg.go
In switch case expressions, the condition on case clause was
not always properly evaluated. Reverse the order of case clause
evaluations (as already done for if-else-if fashion), and fix the
wiring to false-next and true-next nodes.
Fixes #1126.
> interp: fix a wrong control flow in switch

- interp/cfg.go
This is a small change that allows use of composite array literals, such as:
```go
type Vec3 [3]float32
var foo = []Vec3{
{1, 0, 0},
{6, 0, 0},
{6, 2, 0},
{2, 2, 0},
{1, 1, 0},
}
```
> interp: handle binary array literals

- interp/interp_eval_test.go
- interp/run.go
Fixes #1149
Because of how aliases are handled, `n.gen` is set to `getIndexSeqMethod` or `getIndexSeqPtrMethod` in cases like the one described in #1149. As a result, `FieldByIndex` can be called on a value that is not a struct, which causes a panic. This MR updates those two methods to avoid that call if the index array is empty.
> Avoid unnecessary calls to FieldByIndex

- interp/interp_eval_test.go
- interp/run.go
- interp/type.go
Fixes #1150
1. When resolving a selector expression involving an aliased type, resolve the aliased type
2. When building an array literal, resolve the aliased type
Aliases of named array and slice types were the only ones that didn't work, but I added the other test cases for the sake of completeness and through testing.
> Correctly resolve type aliases when building array literals

- _test/issue-1136.go
- interp/cfg.go
- interp/type.go
This allows to fix the reassignment of an non empty interface value.
Before, reassignment was limited to empty interfaces.
Fixes #1138.
> interp: preserve concrete type when converting type to interface

- _test/issue-1145.go
- interp/cfg.go
- interp/type.go
- interp/value.go
In typecheck.go, detect binary methods so we know when to skip the receiver as first parameter when checking function signatures. The signature check is not yet performed, we just avoid a false error.
In cfg.go, take care to label types with isBinMethod field to true whenever a binary method is resolved.
Also, do not attempt to wrap node in functions if the node value is already a binary function.
Fixes #1145.
> interp: fix assign of function values with binary methods

- interp/cfg.go
- interp/interp_eval_test.go
Fixes #1151
If I add a package with `Use` and import it with `ImportUsed`, the package is added to the universe scope as `<pkg>`. If I import with `Eval`, the package is added as `<pkg>/_.go`. However, `(*node).isType` (in cfg.go) only checks for `<pkg>/_.go`. Thus, packages imported with `ImportUsed` can be inaccessible.
This MR updates `(*node).isType` to fall back to `<pkg>` if `<pkg>/_.go` does not exist.
> Fix handling of ImportUsed packages

- cmd/yaegi/run.go
- cmd/yaegi/test.go
- example/closure/closure_test.go
- example/getfunc/getfunc_test.go
- example/pkg/pkg_test.go
- interp/interp.go
- interp/interp_consistent_test.go
- interp/interp_eval_test.go
- interp/interp_export_test.go
- interp/interp_file_test.go
- interp/self_example_test.go
#1102 changed how `Interpreter.Use` interprets export paths such that the last path component is stripped and used as the package name. This resulted in #1139 - attempting to Use an export with only one path component, such as `foo`, would result in the import path being `.`.
This PR changes the signature of `Interpreter.Use` from `Use(Exports)` to `Use(Exports) error`.
With this PR, if Use is called with an incomplete export path, such as `foo`, Use will return an error.
> Update Interpreter.Use API

- _test/issue-1156.go
- interp/cfg.go
- interp/run.go
- interp/type.go
In selector resolution, struct field matching now precedes
method matching. Before struct field matching could be skipped
in case of a matching method, which is incorrect, as demontrated
by _test/issue-1156.go.
Field lookup has been fixed to operate on recursive structures.
Concrete type values are derived when filling a receiver for
interface methods.
LookupBinField has been fixed to skip non struct values.
LookupMethod has been fixed to iterate on interface values as
well as concrete type values.
Fixes #1156.
> interp: improve handling of interface values

- _test/issue-1163.go
- interp/cfg.go
- interp/type.go
The resolution method was not compliant with the Go specification which
requires to retain the object where the field or method is the most
shallowed.
The detection of ambiguous fields or methods (same depth in different
objects) has also been added.
Fixes #1163.
> interp: improve field and method resolution in presence of collisions.

- _test/issue-1173.go
- interp/cfg.go
- interp/type.go
Avoid shortcuts, and apply regular scoping rules for symbol
resolution when checking for builtin calls.
Fixes #1173.
> interp: fix the detection of builtin calls during parsing

- _test/issue-1175.go
- interp/type.go
In parsing array type declaration, The type check of array size was
restricted to `int`. Broaden the test to accept any valid integer
kind.
Fixes #1175.
> interp: fix array declaration with a typed constant size

- _test/issue-1179.go
- interp/run.go
Special wrapping of interface value at return is no longer necessary and
must be avoided now.
Fixes #1179.
> interp: fix handling of interface value in forwarding return calls

- _test/issue-1167.go
- interp/cfg.go
- interp/run.go
In that case, the value must be derefenced before extracting
the method by index, otherwise an incorrect method is returned.
Fixes #1167.
> interp: fix method resolution on pointer to binary values

- _test/issue-1181.go
- interp/cfg.go
The optimization in unary operaror bypasses the necessary temporary
variable in that case and must be disabled.
Fixes #1181.
> interp: fix swap assign with extra operation

- _test/issue-1185.go
- interp/run.go
Interface wrappers were not properly generated.
Fixes #1185
> interp: fix append of values to an array of interface objects

- _test/interface52.go
- interp/run.go
Add early detection of cases where no wrapper is necessary because
the value type already implements the target interface.
It should both increase performances by avoiding the wrapper overhead,
and fix errors due to replacing valid values by incomplete wrappers,
caused by the presence of private methods in the interface definition,
as in #1191.
Fixes #1191.
> interp: fix interface wrapper generation

- internal/cmd/genop/genop.go
- interp/interp_eval_test.go
- interp/op.go
When operating on map elements, result of assign operators were not
written to the map entry. Now check if the destination of an assign
operator is in a map, and if so, set the result to it.
Fixes #1194.
> interp: fix map update by assign operators

- _test/issue-1189.go
- interp/run.go
Map handling builtins getIndexMap and rangeMap had some leftover
code of previous way of emulating interfaces, which was modified
following changes in #1017.
Specific code for interfaceT is removed, as not necessary anymore.
Map builtins are now simplified and more robust.
Fixes #1189.
> interp: fix handling map of interfaces

- _test/issue-1128.go
- _test/issue-1187.go
- interp/cfg.go
- interp/interp.go
- interp/run.go
- interp/value.go
Add getConcreteType to retrieve the concrete type of a nested interface
value implementing a specific interface for which a wrapper exists.
If method resolution fails at runtime, a panic is now issued instead
of an error message and continue.
Fixes #1187.
> interp: support wrapping of nested interfaces

- _test/issue-1208.go
- interp/run.go
Wrap non empty interface value  in struct field, to allow method
lookup.
Fixes #1208.
> interp: improve handling of interface struct field

- _test/struct60.go
- interp/run.go
When calling a function, if the input param is a "zero" instance, it is not set on the input. This is an issue where the param is an `interface{}` as a `nil` value is set instead of the zero value.
The actual solution for this is to remove the `if !val.IsZero()`, this however runs into an issue on `_test/struct48.go` where we have a zero recursive struct instance (`*interface{}`) and we have no way to get its real type. Should a way be figured out to keep tabs on the original type, the `if` can go away, and in the zero case of `genValueRecursiveInterfacePtrValue`, the actual zero type can be returned. 
Fixes #1215
> feat: fix zero instance issue

- _test/fun27.go
- interp/ast.go
- interp/value.go
Set node address in `val` field at creation of `funcDecl` node so it can be used correctly at closure generation, even in the case of forward function declarations, where the value was zero.
Fixes #1214
> interp: fix handling of forward function declaration

- _test/unsafe6.go
- _test/unsafe7.go
- interp/interp_consistent_test.go
- stdlib/unsafe/unsafe_go1.17.go
This adds support for go1.17 `unsafe.Add` and `unsafe.Slice`.
> stdlib: support go1.17 unsafe functions

- internal/unsafe2/unsafe.go
- internal/unsafe2/unsafe_test.go
- interp/run.go
- interp/type.go
- interp/typecheck.go
- interp/value.go
As the unsafe and pointer methods in `reflect` are to be depreciated, and seeing no replacement functions, it is now forced that some unsafe is needed to replace this as when and interface is dereferenced it is made unsettable by reflect.
With this in mind, this adds real recursive types by hot swapping the struct field type on the fly. This removes a lot of compensation code, simplifying all previous cases.
**Note:** While the struct field type is swapped for the real type, the type string is not changed. Due to this, unsafe will recreate the same type.
> interp: create real recursive types with unsafe type swapping

- interp/gta.go
- interp/interp.go
- interp/src.go
- interp/type.go
It was initially assumed that `nodeType` needed to rebuild the type from scratch, but this is not the case anymore. The existing type constructors are now used in `nodeType` to make it more readable. In doing this some bugs in type strings were found and fixed, along with adding the real package name to the type.
As `ptrOf` is now the only place that pointer types are constructed, it is feasible to cache the pointer type on the value type. To ensures that we have a consistent pointer type for any value type.
> interp: make use of type constructors

- _test/rune2.go
- interp/type.go
When using an untyped rune in an interface, the default type was blindly untyping it. This fixes this issue.
Fixes #1238
> interp: fix default types for runes

- _test/assert2.go
- interp/run.go
- interp/value.go
This test (assert2.go) display 2 separate issues:
1. assert2.go L28: Type assert tries to set an `interface{}` to a `valueInterface`. The typing here is complex, we have a valueT(strings.Builder) wrapped in a ptrT wrapped in a src iface wrapped in a valueT(interface{}). Type assert fails to realise that the `valueT` `interface{}` is wrapping the `valueInterface`.
2. assert2.go L29: `genValueBinMethodOnInterface` does not try and get the bin method, as the `typ.node` (`ptrT` or a `valueT`(`string.Builder`)) is set. In this case the src iface is called with a receiver argument. To fix this the method is looked for first if possible, and only if not found does it fall back to the `defaultGen`.
Fixes #1227
> interp: improve handling of wrapped interface values

- _test/const26.go
- interp/gta.go
When a const is late binding and specified with a type, the GTA defineStmt was creating the symbol with the current scopes `iota` which is incorrect. The symbol should be created with the source nodes `rval`.
Related to #1158
> interp: fix parsing of late binding consts

- _test/alias3.go
- _test/alias3/alias3.go
- interp/gta.go
- interp/type.go
When `nodeType` recovers names and methods, it can overwrite the data if the type is an aliasT. When aliasing a type, do not recover the methods, this will be done in the GTA typeSpec pass.
Related to #1158
> interp: types should not recover data for aliases

- _test/composite18.go
- _test/composite19.go
- interp/value.go
When a nil are used in a func composite literal, the nil type is a `func` not a `*node`. This handles this case.
Fixes #1249
> interp: fix nil funcs in composite literals

- interp/cfg.go
- interp/gta.go
- interp/type.go
- interp/typecheck.go
Make sure to keep always a single copy of incomplete type structures.
Remove remnants of recursive types processing.
Now `import "go.uber.org/zap"` works again (see #1172), fixing regressions
introduced since #1236.
> interp: improve processing of recursive types

- _test/alias3.go
- _test/alias3/alias3.go
- _test/selector-scope0.go
- interp/type.go
The current `nodeType` selector precedence is heavy handed in favour of package type. It seems to often create `typeSym` symbols as variable types in the scope will never be found. To fix this if the ancestor node is a field expression, the package type is searched for. After this, if the type is still `nil` the normal scope is searched using `nodeType2`.
Fixes #1158
> interp: fix type selector precedence

- _test/method38.go
- _test/method38/a.go
- _test/method38/b.go
- _test/method39.go
- interp/gta.go
- interp/interp.go
- interp/interp_consistent_test.go
When a define statement relies on a selector or type that may exist in another file it should revisit once GTA is complete. This allows that revisit.
**Note:** In order to keep the original GTA error for the define statement, so the error received is correct and meaningful, I have added a node `meta` property. I decided to make it generic as it may be useful in future. There may be a better way to stash errors across the GTA runs and am open to suggestion here.
Fixes #1253
> interp: allow GTA revisit for unresolved define statements

- _test/type27.go
- _test/type28.go
- _test/type29.go
- _test/type30.go
- _test/type31.go
- _test/type32.go
- _test/type33.go
- interp/ast.go
- interp/gta.go
- interp/interp_consistent_test.go
This supports type spec assign types which disallows the attachment of methods onto the alias type as per the Go spec.
Fixes #1154
> interp: support type spec assign

- interp/ast.go
- interp/compile_test.go
- interp/interp.go
- interp/program.go
- interp/src.go
Adds CompileAST, which can be used to compile Go AST directly. This
allows users to delegate parsing of source to their own code instead of
relying on the interpreter.
CLoses #1251
> interp: add a function to directly compile Go AST

- _test/alias4.go
- interp/cfg.go
- interp/type.go
When dealing with an alias of an alias, the actual underlying type of the source alias should be used.
> interp: handle alias of an alias

- internal/cmd/genop/genop.go
- interp/interp_eval_test.go
- interp/op.go
At generation of operator closures, the comparison expression
was hard-coded instead of being derived from the operator name,
leading to a wrong result.
Fixes #1297.
> interp: fix comparison operators in if statement

- _test/issue-1300.go
- interp/cfg.go
disable the optimization of skipping assign operation in that case,
as this step is necessary in case of writing to a pointer.
Fixes #1300.
> interp: fix assignment to a dereferenced struct pointer

- cmd/yaegi/run.go
- cmd/yaegi/test.go
- interp/interp.go
- interp/interp_eval_test.go
In restricted mode, replace environment related symbols in
stdlib os package by a version which operates on a private copy
per interpreter context.
It allows to have concurrent interpreters in the same process
operating each in their own environment without affecting each
other or the host.
If unrestricted opt is set, this behaviour is disabled, and the
default symbols from stdlib are used.
Note also that no modification is done for syscall package, as it
should be not used in restricted mode.
> interp: virtualize environment in restricted mode

- _test/issue-1306.go
- interp/cfg.go
> interp: avoid collision between type and variable names in assign

- _test/issue-1311.go
- interp/cfg.go
- interp/run.go
A runtime builtin assignFromCall is added to handle multiple values returned at once. It is necessary if some of the values require to be set to interface values in the caller space, which is performed by reflect.Set in assignFromCall.
Fixes #1311.
> interp: fix assign of multiple return function call

- _test/issue-1315.go
- interp/run.go
Fixes #1315.
With this PR, the package gopkg.in/yaml.v3 works in yaegi (fixes #1296).
> interp: fix type switch when the case type is an interpreted interface

- _test/issue-1330.go
- interp/interp_consistent_test.go
- interp/run.go
The capability to dereference pointers has been added to
methodByName(), improving method lookup on binary values.
Wrapping to valueInterface is performed in a missing use case at
return of function calls. It was done in the nested call, but not
at assign.
Fixes #1330.
> interp: improve method resolution on embedded fields

- _test/issue-1333.go
- interp/run.go
> interp: fix wrapping of returned closure passed to runtime

- _test/issue-1361.go
- interp/run.go
- interp/value.go
Wrap binary function values in a node if passing it
as a parameter to an interperter defined function.
Fixes #1361.
> interp: fix passing binary function as parameter

- _test/issue-1365.go
- _test/var16.go
- interp/cfg.go
In a statement like `a, b := f()` if `a` was previously declared,
and has the same type, its symbol must be reused, a new symbol must not override its
previous value. This is now fixed.
Fixes #1365.
> interp: fix handling of redeclaration in multi-assign expression

- _test/issue-1368.go
- interp/cfg.go
The control flow graph was incorrect for the initial clause.
Fixes #1368.
> interp: fix switch expression

- _test/issue-1373.go
- interp/typecheck.go
> Ignore private methods for binary types during type assertion

- interp/compile_test.go
- interp/interp_eval_test.go
- interp/program.go
The interpreter has its own internal fileset and expects all code to have been parsed using that fileset. If a user creates a fileset, calls `go/parser.Parse*`, then passes the result to `interp.CompileAST`, strange things can happen.
The solutions I can see are:
1. Expose the fileset so the user can use it when parsing source.
2. Add the fileset as an option (input to New) so that the user can tell the interpreter to use a specific fileset.
3. Pass the fileset into `CompileAST`
There are two ways to implement option 3. One is to add a field to nodes and update every reference to `interp.fset` to use `node.fset`. The other is to add a parameter to every function that references `interp.fset` or calls a function that does. Both of these are significant changes and involve an extra pointer …
> interp: expose fset to fix CompileAST issue

- interp/interp_test.go
- interp/scope.go
Closes #1385. Add `func (*Interpreter) Globals() map[string]reflect.Value` which returns a map of the global variables and constants declared in `package main`.
> interp: add a function to get globals

- interp/gta.go
- interp/interp_eval_test.go
Closes #1388. When a package is imported, it creates a symbol with a name like `"errors/_.go"`. If a statement such as `x := errors.New(...)` is executed before `import "errors"`, it creates an incomplete type symbol with a name like `"errors"`. Importing the package after the incomplete type symbol has been created does not fix the compile issue because the incomplete type still exists.
To fix this, this PR deletes the incomplete type symbol, if one exists.
> interp: delete incomplete type on pkg import

- interp/cfg.go
- interp/gta.go
- interp/interp_eval_test.go
- interp/typecheck.go
We now detect the use of special identifier _ (blank) during parsing in order to abort compiling early. It allows to not panic later during execution. We must catch all the cases where blank is used as a value, but still preserve the cases where it is assigned, used as a struct field or for import side effects.
Fixes #1386.
> interp: detect invalid uses of _ as value

- _test/issue-1381.go
- interp/run.go
- interp/type.go
Use direct assignment instead of reflect.Value Set method to
initialize a binary composite type, as for non binary types.
It ensures that a new reflect.Value is stored in the frame
instead of modifying a possibly existing one, which can defeat
the purpose of initializing variables in a body loop.
While there, remove the need to have and use a mutex on types.
Fixes #1381.
> interp: fix creation of binary composite types

- _test/break0.go
- _test/break1.go
- _test/break2.go
- _test/break3.go
- _test/cont2.go
- _test/cont3.go
- _test/issue-1354.go
- interp/cfg.go
- interp/interp_consistent_test.go
- interp/scope.go
The logic of goto was false due to mixing break label and goto
label, despite being opposite. In case of break, jump to node (the
exit point) instead of node.start. Also always define label symbols
before their use is parsed.
Fixes #1354.
> interp: fix the behaviour of goto, continue and break

- _test/issue-1344.go
- interp/run.go
There should be no need now to wrap empty interfaces in order to
retrieve its value.
Fixes #1344.
> interp: fix handling of empty interfaces in map index expressions

- interp/interp_eval_test.go
- interp/src.go
This avoids panic during import, and print a proper diagnostic
instead.
Fixes #1394.
> interp: implements detection of packages with no Go files

- interp/interp_eval_test.go
- interp/type.go
- interp/typecheck.go
For untyped numerical types, conversions to different numerical
types can be allowed if there is no overflow (not checked here).
Fixes #1402.
> interp: allow conversions of untyped complex

- interp/interp_eval_test.go
- interp/value.go
In REPL mode, a panic (stack overflow) could be triggered by:
$ yaegi
> a:
runtime: goroutine stack exceeds 1000000000-byte limit
runtime: sp=0x14020760330 stack=[0x14020760000, 0x14040760000]
fatal error: stack overflow
[...]
This issue occurs in incremental parsing mode only, and not when the parser
is in file mode. We avoid it by being more defensive when generating
values.
Fixes #982.
> interp: avoid panic when defining a label in incremental parsing mode

- interp/cfg.go
- interp/interp_eval_test.go
- interp/run.go
In that case, the interface must be wrapped in an valueInterface
at creation.
With that fix, it is now possible to import
github.com/google/go-querystring/query. Not tested beyond that.
Fixes #1123.
> interp: create interpreter interface value with new

- _test/issue-435.go
- interp/interp.go
- interp/run.go
- interp/value.go
- stdlib/maptypes.go
- stdlib/stdlib.go
We finally address a long standing limitation of the interpreter:
the capacity to generate the correct interface wrapper for an
anonymous interface{} function parameter of a binary function.
It allows for example fmt.Printf to invoke the String method
of an object defined within the interpreter, or json.Marshal
to invoke a textMarshaler method if it exists and if there is
no Marshaler method already defined for the passed interpreter
object.
To achieve that, we add a new mapType part of the "Used" symbols
to describe what not empty interfaces are expected and in which
priority order. This information can not be guessed and is found
in the related package documentation, then captured in stdlib/maptypes.go.
Then, at compile time and/or during execution, a lookup on mapTypes
is performed to …
> interp: improve the behaviour of interface{} function parameters

- interp/interp_eval_test.go
- interp/typecheck.go
The check for mismatched types was already added recently for ==  and != comparisons.
This PR now adds it for other comparisons ( < , <=, > , >=).
> interp: catch mismatched types for other comparisons

- _test/issue-1411.go
- interp/cfg.go
- interp/type.go
The type.val field was always pointing to the final underlying type
for aliased types, defeating a possible match if a method was
attached to a type in between. Now the complete chain of aliases
is always preserved.
We have added an underlying() itype method which returns the underlying
type of a defined type (aliasT), even in the presence of multiple
indirections.
We have added a definedType function which checks if type t1 is
defined from type t2 or t2 defined from t1, required when checking
assignability of aliasT types.
Fixes #1411.
PS: this is the 2nd attempt, as the first version #1412 wasn't passing
_test/issue-1408.go as well. This PR does pass and supersedes #1412.
> interp: fix resolution of methods on aliased types

- _test/alias3/alias3.go
- _test/alias4.go
- interp/cfg.go
I expect the following code to be supported.
```go
type TT http.Header
func (t TT) Set(key, val string) {
}
func (t TT) Get(key string) string {
}
```
So, I pushed this PR. 
Do I need to add some test cases?  I don't see the relevant test files ....
> interp: improve support of alias types

- interp/cfg.go
- interp/interp_eval_test.go
Such function declaration denotes either a linkname (an access to
an arbitrary, typically unexported symbol, solved by go compiler),
or a foreign C or assembly implementation of the body.
Those cases are not supported (or planned to be) by the interpreter.
Fixes #1431.
> interp: do not allow function declaration without body

- _test/gen1.go
- _test/gen2.go
- _test/gen3.go
- _test/gen4.go
- _test/gen5.go
- _test/gen6.go
- _test/gen7.go
- _test/gen8.go
- _test/gen9.go
- interp/ast.go
- interp/cfg.go
- interp/compile_test.go
- interp/generic.go
- interp/gta.go
- interp/interp.go
- interp/interp_consistent_test.go
- interp/scope.go
- interp/type.go
- interp/typecheck.go
> interp: add support of Go generics in interpreter

- _test/p4/p4.go
- _test/p5.go
- _test/p5/p5.go
- interp/cfg.go
The variable dependency check function was confused by a dependency
variable with the same name but in an external package.
This change is necessary to address #1427.
> interp: fix spurious variable declaration loop

- _test/issue-1425.go
- internal/cmd/extract/extract.go
- interp/doc.go
- interp/interp.go
- interp/interp_export_test.go
- interp/run.go
- interp/scope.go
- interp/use.go
- stdlib/wrapper-composed.go
This change implements a workaround to better support composed
interfaces in yaegi and let the interpreter define objects which
implement multiple interfaces at once.
We use the existing MapTypes to store what possible composed interface
wrapper could be used for some interfaces. When generating an interface
wrapper, the wrapper with the highest number of implemented methods is
chosen.
This is still an imperfect solution but it improves the accuracy of
interpreter in some critical cases.
This workaround could be removed in future if/when golang/go#15924
is resolved.
Fixes #1425.
> interp: improve handling of composed interfaces wrappers

- _test/switch39.go
- _test/switch40.go
- interp/cfg.go
If the value on which to type-switch was already set (i.e. a variable),
there was no problem. But if it had to be obtained through a complex
expression (func call, array index, etc...), then the code to retrieve
the value prior type-switch was not scheduled. This is now fixed.
This issue is nasty because the behavior is silently changed,
leading potentially to further unrelated issues or runtime panics.
Fixes #1444.
> interp: fix type switch on arbitrary expressions

- _test/assert2.go
- _test/issue-1447.go
- interp/run.go
- interp/type.go
- interp/typecheck.go
- interp/value.go
The representation of non empty interfaces defined in the interpreter is now identical between refType() and frameType() functions, which are used to generate interpreter objects.
Fixes #1447 and #1426.
> interp: fix use of interfaces in composite types

- _test/issue-1451.go
- interp/type.go
> interp: add missing conversion for non integer array dimension

- _test/issue-1454.go
- interp/cfg.go
- interp/type.go
- interp/typecheck.go
In type assertion at compile time, compare signatures between function types only.
Make `itype.numOut()` return the correct value for Go builtins (this was not strictly necessary due to above fix, but it is correct and improves maintainability).
Fixes #1454.
> interp: improve type assertions

- _test/issue-1460.go
- interp/gta.go
- interp/type.go
Those declarations involve the indexListExpr AST token, which was not handled in type.go. The same processing as for a single type parameter is applied.
Fixes #1460.
> interp: fix handling generic types with multiple type parameters

- interp/typecheck.go
This fixes an issue where two untyped values with different `itype` could not be operated on.
Minimal example to reproduce this:
```
package main
import "math"
func main() {
println(math.MaxFloat64 - 1.0)
}
```
Result: `invalid operation: mismatched types untyped float64 and untyped float`, but should be `1.7976931348623157e+308`
> fix: ensure that untyped values are converted to the same type

- _test/type34.go
- interp/run.go
- interp/type.go
Fields of types that are aliases are not always resolved correctly, especially if the aliased type is itself an alias.
A minimal example is:
```
package main
type original struct {
Field string
}
func main() {
type alias original
type alias2 alias
var a = &alias2{
Field: "test",
}
println(a.Field)
}
```
There is already a method (`baseType`) for resolving the underlying struct type; but it isn't always used previous to this change.
> fix: correctly resolve fields of aliased structs
